// snippet.hide
// Code generated by sidekick. DO NOT EDIT.
//
// Copyright  Google LLC

// snippet.show
import GoogleCloudLocation
import GoogleCloudWkt
import GoogleIamV1
import GoogleCloudSecretmanagerV1
import Foundation

func sample(client: some SecretManagerService) async throws {
  let response = try await client.createSecret(
    request: CreateSecretRequest( /* set fields */)
  )
  print("Success: \(response)")
}
// snippet.hide

@main
struct SnippetRunner {
  static func main() async throws {
    do {
      let client = try GoogleCloudSecretmanagerV1.Clients.SecretManagerServiceClient()
      try await sample(client: client)
    } catch {
      print("Error: \(error)")
    }
  }
}
