// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Request message for
/// [SecretManagerService.CreateSecret][google.cloud.secretmanager.v1.SecretManagerService.CreateSecret].
///
/// [google.cloud.secretmanager.v1.SecretManagerService.CreateSecret]: <doc:SecretManagerServiceClient/createSecret(request:options:)>
public struct CreateSecretRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The resource name of the project to associate with the
  /// [Secret][google.cloud.secretmanager.v1.Secret], in the format `projects/*`
  /// or `projects/*/locations/*`.
  ///
  /// [google.cloud.secretmanager.v1.Secret]: <doc:Secret>
  public var parent: Swift.String = Swift.String()

  /// Required. This must be unique within the project.
  ///
  /// A secret ID is a string with a maximum length of 255 characters and can
  /// contain uppercase and lowercase letters, numerals, and the hyphen (`-`) and
  /// underscore (`_`) characters.
  public var secretId: Swift.String = Swift.String()

  /// Required. A [Secret][google.cloud.secretmanager.v1.Secret] with initial
  /// field values.
  ///
  /// [google.cloud.secretmanager.v1.Secret]: <doc:Secret>
  public var secret: Secret? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `CreateSecretRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CreateSecretRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let parent = CodingKeys(stringValue: "parent")
    static let secretId = CodingKeys(stringValue: "secretId")
    static let secret = CodingKeys(stringValue: "secret")

    static let _knownKeys: Set<Swift.String> = [
      "parent",
      "secretId",
      "secret",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .parent) {
      self.parent = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .secretId) {
      self.secretId = value
    }
    self.secret = try container.decodeIfPresent(Secret.self, forKey: .secret)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.parent, forKey: .parent)
    try container.encode(self.secretId, forKey: .secretId)
    try container.encodeIfPresent(self.secret, forKey: .secret)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.secretmanager.v1.CreateSecretRequest"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
