// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request message for
/// [SecretManagerService.CreateSecret][google.cloud.secretmanager.v1.SecretManagerService.CreateSecret].
///
/// [google.cloud.secretmanager.v1.SecretManagerService.CreateSecret]: <doc:SecretManagerService/createSecret(request:)>
public struct CreateSecretRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The resource name of the project to associate with the
  /// [Secret][google.cloud.secretmanager.v1.Secret], in the format `projects/*`
  /// or `projects/*/locations/*`.
  ///
  /// [google.cloud.secretmanager.v1.Secret]: <doc:Secret>
  public var parent: Swift.String

  /// Required. This must be unique within the project.
  ///
  /// A secret ID is a string with a maximum length of 255 characters and can
  /// contain uppercase and lowercase letters, numerals, and the hyphen (`-`) and
  /// underscore (`_`) characters.
  public var secretId: Swift.String

  /// Required. A [Secret][google.cloud.secretmanager.v1.Secret] with initial
  /// field values.
  ///
  /// [google.cloud.secretmanager.v1.Secret]: <doc:Secret>
  public var secret: Secret?

  /// Initialize a new instance of `CreateSecretRequest`.
  public init(
    parent: Swift.String = Swift.String(),
    secretId: Swift.String = Swift.String(),
    secret: Secret? = nil,
  ) {
    self.parent = parent
    self.secretId = secretId
    self.secret = secret
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.secretmanager.v1.CreateSecretRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
