// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Configuration for encrypting secret payloads using customer-managed
/// encryption keys (CMEK).
public struct CustomerManagedEncryption: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. The resource name of the Cloud KMS CryptoKey used to encrypt
  /// secret payloads.
  ///
  /// For secrets using the
  /// [UserManaged][google.cloud.secretmanager.v1.Replication.UserManaged]
  /// replication policy type, Cloud KMS CryptoKeys must reside in the same
  /// location as the [replica location][Secret.UserManaged.Replica.location].
  ///
  /// For secrets using the
  /// [Automatic][google.cloud.secretmanager.v1.Replication.Automatic]
  /// replication policy type, Cloud KMS CryptoKeys must reside in `global`.
  ///
  /// The expected format is `projects/*/locations/*/keyRings/*/cryptoKeys/*`.
  ///
  /// [google.cloud.secretmanager.v1.Replication.Automatic]: <doc:Replication/Automatic>
  /// [google.cloud.secretmanager.v1.Replication.UserManaged]: <doc:Replication/UserManaged>
  public var kmsKeyName: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `CustomerManagedEncryption`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CustomerManagedEncryption().with { $0.kmsKeyName = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let kmsKeyName = CodingKeys(stringValue: "kmsKeyName")

    static let _knownKeys: Set<Swift.String> = [
      "kmsKeyName"
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .kmsKeyName) {
      self.kmsKeyName = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.kmsKeyName, forKey: .kmsKeyName)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.secretmanager.v1.CustomerManagedEncryption"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
