// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

import GoogleCloudLocation
import GoogleCloudWkt
import GoogleIamV1

/// Request message for
/// [SecretManagerService.DeleteSecret][google.cloud.secretmanager.v1.SecretManagerService.DeleteSecret].
///
/// [google.cloud.secretmanager.v1.SecretManagerService.DeleteSecret]: <doc:SecretManagerService/deleteSecret(request:)>
public struct DeleteSecretRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The resource name of the
  /// [Secret][google.cloud.secretmanager.v1.Secret] to delete in the format
  /// `projects/*/secrets/*`.
  ///
  /// [google.cloud.secretmanager.v1.Secret]: <doc:Secret>
  public var name: String

  /// Optional. Etag of the [Secret][google.cloud.secretmanager.v1.Secret]. The
  /// request succeeds if it matches the etag of the currently stored secret
  /// object. If the etag is omitted, the request succeeds.
  ///
  /// [google.cloud.secretmanager.v1.Secret]: <doc:Secret>
  public var etag: String

  /// Initialize a new instance of `DeleteSecretRequest`.
  public init(
    name: String = String(),
    etag: String = String(),
  ) {
    self.name = name
    self.etag = etag
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.secretmanager.v1.DeleteSecretRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
