// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

import GoogleCloudLocation
import GoogleCloudWkt
import GoogleIamV1

/// Request message for
/// [SecretManagerService.DestroySecretVersion][google.cloud.secretmanager.v1.SecretManagerService.DestroySecretVersion].
public struct DestroySecretVersionRequest: Codable, Equatable {
  /// Required. The resource name of the
  /// [SecretVersion][google.cloud.secretmanager.v1.SecretVersion] to destroy in
  /// the format `projects/*/secrets/*/versions/*` or
  /// `projects/*/locations/*/secrets/*/versions/*`.
  public var name: String

  /// Optional. Etag of the
  /// [SecretVersion][google.cloud.secretmanager.v1.SecretVersion]. The request
  /// succeeds if it matches the etag of the currently stored secret version
  /// object. If the etag is omitted, the request succeeds.
  public var etag: String

  /// Initialize a new instance of `DestroySecretVersionRequest`.
  public init(
    name: String = String(),
    etag: String = String(),
  ) {
    self.name = name
    self.etag = etag
  }
}
