// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Request message for
/// [SecretManagerService.EnableManagedRotation][google.cloud.secretmanager.v1.SecretManagerService.EnableManagedRotation].
///
/// [google.cloud.secretmanager.v1.SecretManagerService.EnableManagedRotation]: <doc:SecretManagerServiceClient/enableManagedRotation(request:options:)>
public struct EnableManagedRotationRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The resource name of the
  /// [Secret][google.cloud.secretmanager.v1.Secret] to associate with the
  /// [SecretVersion][google.cloud.secretmanager.v1.SecretVersion] in the format
  /// `projects/*/secrets/*` or `projects/*/locations/*/secrets/*`.
  ///
  /// [google.cloud.secretmanager.v1.Secret]: <doc:Secret>
  /// [google.cloud.secretmanager.v1.SecretVersion]: <doc:SecretVersion>
  public var parent: Swift.String = Swift.String()

  /// The credentials required for Managed Rotation.
  /// Right now, only Cloud SQL Single User credentials are supported.
  public var credentials: OneOf_Credentials? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `EnableManagedRotationRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = EnableManagedRotationRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let parent = CodingKeys(stringValue: "parent")
    static let cloudSqlSingleUserCredentials = CodingKeys(
      stringValue: "cloudSqlSingleUserCredentials")

    static let _knownKeys: Set<Swift.String> = [
      "parent",
      "cloudSqlSingleUserCredentials",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .parent) {
      self.parent = value
    }

    var credentials: OneOf_Credentials? = nil
    let credentialsCheckAndSet = {
      if credentials != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'credentials'"))
      }
      credentials = $0
    }
    if let cloudSqlSingleUserCredentials = try container.decodeIfPresent(
      EnableManagedRotationRequest.CloudSQLSingleUserCredentials?.self,
      forKey: .cloudSqlSingleUserCredentials)
    {
      try credentialsCheckAndSet(.cloudSqlSingleUserCredentials(cloudSqlSingleUserCredentials))
    }
    self.credentials = credentials
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.parent, forKey: .parent)

    if let choice = self.credentials {
      switch choice {
      case .cloudSqlSingleUserCredentials(let value):
        try container.encode(value, forKey: .cloudSqlSingleUserCredentials)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// These are the credentials required for Cloud SQL DB for Single user
  /// Managed Rotation.
  public struct CloudSQLSingleUserCredentials: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Required. Instance ID of the Cloud SQL instance.
    public var instanceId: Swift.String = Swift.String()

    /// Required. Username of the Cloud SQL instance.
    public var username: Swift.String = Swift.String()

    /// Optional. Password of the Cloud SQL instance. If this is not provided,
    /// a random password will be generated.
    public var password: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `CloudSQLSingleUserCredentials`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = CloudSQLSingleUserCredentials().with { $0.instanceId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let instanceId = CodingKeys(stringValue: "instanceId")
      static let username = CodingKeys(stringValue: "username")
      static let password = CodingKeys(stringValue: "password")

      static let _knownKeys: Set<Swift.String> = [
        "instanceId",
        "username",
        "password",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .instanceId) {
        self.instanceId = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .username) {
        self.username = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .password) {
        self.password = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.instanceId, forKey: .instanceId)
      try container.encode(self.username, forKey: .username)
      try container.encode(self.password, forKey: .password)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.secretmanager.v1.EnableManagedRotationRequest.CloudSQLSingleUserCredentials"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// The credentials required for Managed Rotation.
  /// Right now, only Cloud SQL Single User credentials are supported.
  public enum OneOf_Credentials: Codable, Equatable, Sendable {
    /// Credentials required for Cloud SQL DB for Single user Managed Rotation.
    indirect case cloudSqlSingleUserCredentials(
      EnableManagedRotationRequest.CloudSQLSingleUserCredentials?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.secretmanager.v1.EnableManagedRotationRequest"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
