// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Request message for
/// [SecretManagerService.ListSecretVersions][google.cloud.secretmanager.v1.SecretManagerService.ListSecretVersions].
///
/// [google.cloud.secretmanager.v1.SecretManagerService.ListSecretVersions]: <doc:SecretManagerService/listSecretVersions(request:)>
public struct ListSecretVersionsRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The resource name of the
  /// [Secret][google.cloud.secretmanager.v1.Secret] associated with the
  /// [SecretVersions][google.cloud.secretmanager.v1.SecretVersion] to list, in
  /// the format `projects/*/secrets/*` or `projects/*/locations/*/secrets/*`.
  ///
  /// [google.cloud.secretmanager.v1.Secret]: <doc:Secret>
  /// [google.cloud.secretmanager.v1.SecretVersion]: <doc:SecretVersion>
  public var parent: String

  /// Optional. The maximum number of results to be returned in a single page. If
  /// set to 0, the server decides the number of results to return. If the
  /// number is greater than 25000, it is capped at 25000.
  public var pageSize: Int32

  /// Optional. Pagination token, returned earlier via
  /// ListSecretVersionsResponse.next_page_token][].
  public var pageToken: String

  /// Optional. Filter string, adhering to the rules in
  /// [List-operation
  /// filtering](https://cloud.google.com/secret-manager/docs/filtering). List
  /// only secret versions matching the filter. If filter is empty, all secret
  /// versions are listed.
  public var filter: String

  /// Initialize a new instance of `ListSecretVersionsRequest`.
  public init(
    parent: String = String(),
    pageSize: Int32 = Int32(),
    pageToken: String = String(),
    filter: String = String(),
  ) {
    self.parent = parent
    self.pageSize = pageSize
    self.pageToken = pageToken
    self.filter = filter
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.secretmanager.v1.ListSecretVersionsRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
