// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

import GoogleCloudLocation
import GoogleCloudWkt
import GoogleIamV1

/// Response message for
/// [SecretManagerService.ListSecretVersions][google.cloud.secretmanager.v1.SecretManagerService.ListSecretVersions].
public struct ListSecretVersionsResponse: Codable, Equatable {
  /// The list of [SecretVersions][google.cloud.secretmanager.v1.SecretVersion]
  /// sorted in reverse by create_time (newest first).
  public var versions: [SecretVersion]

  /// A token to retrieve the next page of results. Pass this value in
  /// [ListSecretVersionsRequest.page_token][google.cloud.secretmanager.v1.ListSecretVersionsRequest.page_token]
  /// to retrieve the next page.
  public var nextPageToken: String

  /// The total number of
  /// [SecretVersions][google.cloud.secretmanager.v1.SecretVersion] but 0 when
  /// the
  /// [ListSecretsRequest.filter][google.cloud.secretmanager.v1.ListSecretsRequest.filter]
  /// field is set.
  public var totalSize: Int32

  /// Initialize a new instance of `ListSecretVersionsResponse`.
  public init(
    versions: [SecretVersion] = [],
    nextPageToken: String = String(),
    totalSize: Int32 = Int32(),
  ) {
    self.versions = versions
    self.nextPageToken = nextPageToken
    self.totalSize = totalSize
  }
}
