// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudGax
import GoogleCloudWkt

/// Response message for
/// [SecretManagerService.ListSecretVersions][google.cloud.secretmanager.v1.SecretManagerService.ListSecretVersions].
///
/// [google.cloud.secretmanager.v1.SecretManagerService.ListSecretVersions]: <doc:SecretManagerService/listSecretVersions(request:)>
public struct ListSecretVersionsResponse: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  GoogleCloudGax._PaginatedResponse,
  Sendable
{
  /// The list of [SecretVersions][google.cloud.secretmanager.v1.SecretVersion]
  /// sorted in reverse by create_time (newest first).
  ///
  /// [google.cloud.secretmanager.v1.SecretVersion]: <doc:SecretVersion>
  public var versions: [SecretVersion]

  /// A token to retrieve the next page of results. Pass this value in
  /// [ListSecretVersionsRequest.page_token][google.cloud.secretmanager.v1.ListSecretVersionsRequest.page_token]
  /// to retrieve the next page.
  ///
  /// [google.cloud.secretmanager.v1.ListSecretVersionsRequest.page_token]: <doc:ListSecretVersionsRequest/pageToken>
  public var nextPageToken: String

  /// The total number of
  /// [SecretVersions][google.cloud.secretmanager.v1.SecretVersion] but 0 when
  /// the
  /// [ListSecretsRequest.filter][google.cloud.secretmanager.v1.ListSecretsRequest.filter]
  /// field is set.
  ///
  /// [google.cloud.secretmanager.v1.ListSecretsRequest.filter]: <doc:ListSecretsRequest/filter>
  /// [google.cloud.secretmanager.v1.SecretVersion]: <doc:SecretVersion>
  public var totalSize: Int32

  /// Initialize a new instance of `ListSecretVersionsResponse`.
  public init(
    versions: [SecretVersion] = [],
    nextPageToken: String = String(),
    totalSize: Int32 = Int32(),
  ) {
    self.versions = versions
    self.nextPageToken = nextPageToken
    self.totalSize = totalSize
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.secretmanager.v1.ListSecretVersionsResponse"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }

  public func _getPaginatedItems() -> [SecretVersion] {
    return self.versions
  }
}
