// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

import GoogleCloudLocation
import GoogleCloudWkt
import GoogleIamV1

/// Response message for
/// [SecretManagerService.ListSecrets][google.cloud.secretmanager.v1.SecretManagerService.ListSecrets].
public struct ListSecretsResponse: Codable, Equatable, GoogleCloudWkt._AnyPackable, Sendable {
  /// The list of [Secrets][google.cloud.secretmanager.v1.Secret] sorted in
  /// reverse by create_time (newest first).
  public var secrets: [Secret]

  /// A token to retrieve the next page of results. Pass this value in
  /// [ListSecretsRequest.page_token][google.cloud.secretmanager.v1.ListSecretsRequest.page_token]
  /// to retrieve the next page.
  public var nextPageToken: String

  /// The total number of [Secrets][google.cloud.secretmanager.v1.Secret] but 0
  /// when the
  /// [ListSecretsRequest.filter][google.cloud.secretmanager.v1.ListSecretsRequest.filter]
  /// field is set.
  public var totalSize: Int32

  /// Initialize a new instance of `ListSecretsResponse`.
  public init(
    secrets: [Secret] = [],
    nextPageToken: String = String(),
    totalSize: Int32 = Int32(),
  ) {
    self.secrets = secrets
    self.nextPageToken = nextPageToken
    self.totalSize = totalSize
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.secretmanager.v1.ListSecretsResponse"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
