// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The replication status of a
/// [SecretVersion][google.cloud.secretmanager.v1.SecretVersion].
///
/// [google.cloud.secretmanager.v1.SecretVersion]: <doc:SecretVersion>
public struct ReplicationStatus: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The replication status of the
  /// [SecretVersion][google.cloud.secretmanager.v1.SecretVersion].
  ///
  /// [google.cloud.secretmanager.v1.SecretVersion]: <doc:SecretVersion>
  public var replicationStatus: OneOf_ReplicationStatus? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ReplicationStatus`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ReplicationStatus().with { $0.automatic = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let automatic = CodingKeys(stringValue: "automatic")
    static let userManaged = CodingKeys(stringValue: "userManaged")

    static let _knownKeys: Set<Swift.String> = [
      "automatic",
      "userManaged",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var replicationStatus: OneOf_ReplicationStatus? = nil
    let replicationStatusCheckAndSet = {
      if replicationStatus != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'replicationStatus'"))
      }
      replicationStatus = $0
    }
    if let automatic = try container.decodeIfPresent(
      ReplicationStatus.AutomaticStatus?.self, forKey: .automatic)
    {
      try replicationStatusCheckAndSet(.automatic(automatic))
    }
    if let userManaged = try container.decodeIfPresent(
      ReplicationStatus.UserManagedStatus?.self, forKey: .userManaged)
    {
      try replicationStatusCheckAndSet(.userManaged(userManaged))
    }
    self.replicationStatus = replicationStatus
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.replicationStatus {
      switch choice {
      case .automatic(let value):
        try container.encode(value, forKey: .automatic)
      case .userManaged(let value):
        try container.encode(value, forKey: .userManaged)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The replication status of a
  /// [SecretVersion][google.cloud.secretmanager.v1.SecretVersion] using
  /// automatic replication.
  ///
  /// Only populated if the parent [Secret][google.cloud.secretmanager.v1.Secret]
  /// has an automatic replication policy.
  ///
  /// [google.cloud.secretmanager.v1.Secret]: <doc:Secret>
  /// [google.cloud.secretmanager.v1.SecretVersion]: <doc:SecretVersion>
  public struct AutomaticStatus: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Output only. The customer-managed encryption status of the
    /// [SecretVersion][google.cloud.secretmanager.v1.SecretVersion]. Only
    /// populated if customer-managed encryption is used.
    ///
    /// [google.cloud.secretmanager.v1.SecretVersion]: <doc:SecretVersion>
    public var customerManagedEncryption: CustomerManagedEncryptionStatus? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `AutomaticStatus`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = AutomaticStatus().with { $0.customerManagedEncryption = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let customerManagedEncryption = CodingKeys(stringValue: "customerManagedEncryption")

      static let _knownKeys: Set<Swift.String> = [
        "customerManagedEncryption"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.customerManagedEncryption = try container.decodeIfPresent(
        CustomerManagedEncryptionStatus.self, forKey: .customerManagedEncryption)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(
        self.customerManagedEncryption, forKey: .customerManagedEncryption)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.secretmanager.v1.ReplicationStatus.AutomaticStatus"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// The replication status of a
  /// [SecretVersion][google.cloud.secretmanager.v1.SecretVersion] using
  /// user-managed replication.
  ///
  /// Only populated if the parent [Secret][google.cloud.secretmanager.v1.Secret]
  /// has a user-managed replication policy.
  ///
  /// [google.cloud.secretmanager.v1.Secret]: <doc:Secret>
  /// [google.cloud.secretmanager.v1.SecretVersion]: <doc:SecretVersion>
  public struct UserManagedStatus: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Output only. The list of replica statuses for the
    /// [SecretVersion][google.cloud.secretmanager.v1.SecretVersion].
    ///
    /// [google.cloud.secretmanager.v1.SecretVersion]: <doc:SecretVersion>
    public var replicas: [ReplicationStatus.UserManagedStatus.ReplicaStatus] = []

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `UserManagedStatus`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = UserManagedStatus().with { $0.replicas = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let replicas = CodingKeys(stringValue: "replicas")

      static let _knownKeys: Set<Swift.String> = [
        "replicas"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(
        [ReplicationStatus.UserManagedStatus.ReplicaStatus].self, forKey: .replicas)
      {
        self.replicas = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.replicas, forKey: .replicas)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// Describes the status of a user-managed replica for the
    /// [SecretVersion][google.cloud.secretmanager.v1.SecretVersion].
    ///
    /// [google.cloud.secretmanager.v1.SecretVersion]: <doc:SecretVersion>
    public struct ReplicaStatus: Codable, Equatable, GoogleWKT._AnyPackable,
      Sendable
    {
      /// Output only. The canonical ID of the replica location.
      /// For example: `"us-east1"`.
      public var location: Swift.String = Swift.String()

      /// Output only. The customer-managed encryption status of the
      /// [SecretVersion][google.cloud.secretmanager.v1.SecretVersion]. Only
      /// populated if customer-managed encryption is used.
      ///
      /// [google.cloud.secretmanager.v1.SecretVersion]: <doc:SecretVersion>
      public var customerManagedEncryption: CustomerManagedEncryptionStatus? = nil

      @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

      /// Initialize a new instance of `ReplicaStatus`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = ReplicaStatus().with { $0.location = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private struct CodingKeys: CodingKey {
        var stringValue: Swift.String
        var intValue: Swift.Int? { nil }
        init(stringValue: Swift.String) { self.stringValue = stringValue }
        init?(intValue: Swift.Int) { nil }

        static let location = CodingKeys(stringValue: "location")
        static let customerManagedEncryption = CodingKeys(stringValue: "customerManagedEncryption")

        static let _knownKeys: Set<Swift.String> = [
          "location",
          "customerManagedEncryption",
        ]
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        if let value = try container.decodeIfPresent(Swift.String.self, forKey: .location) {
          self.location = value
        }
        self.customerManagedEncryption = try container.decodeIfPresent(
          CustomerManagedEncryptionStatus.self, forKey: .customerManagedEncryption)
        for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
          self._unknownFields.json[key.stringValue] = try container.decode(
            GoogleWKT.WKTValue.self, forKey: key)
        }
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.location, forKey: .location)
        try container.encodeIfPresent(
          self.customerManagedEncryption, forKey: .customerManagedEncryption)
        for (key, value) in self._unknownFields.json {
          try container.encode(value, forKey: CodingKeys(stringValue: key))
        }
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.secretmanager.v1.ReplicationStatus.UserManagedStatus.ReplicaStatus"
      }
      public init(fromAny any: GoogleWKT.WKTAny) throws {
        self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleWKT.WKTStruct {
        return try GoogleWKT._slowAnySerialize(message: self)
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.secretmanager.v1.ReplicationStatus.UserManagedStatus"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// The replication status of the
  /// [SecretVersion][google.cloud.secretmanager.v1.SecretVersion].
  ///
  /// [google.cloud.secretmanager.v1.SecretVersion]: <doc:SecretVersion>
  public enum OneOf_ReplicationStatus: Codable, Equatable, Sendable {
    /// Describes the replication status of a
    /// [SecretVersion][google.cloud.secretmanager.v1.SecretVersion] with
    /// automatic replication.
    ///
    /// Only populated if the parent
    /// [Secret][google.cloud.secretmanager.v1.Secret] has an automatic
    /// replication policy.
    ///
    /// [google.cloud.secretmanager.v1.Secret]: <doc:Secret>
    /// [google.cloud.secretmanager.v1.SecretVersion]: <doc:SecretVersion>
    indirect case automatic(ReplicationStatus.AutomaticStatus?)
    /// Describes the replication status of a
    /// [SecretVersion][google.cloud.secretmanager.v1.SecretVersion] with
    /// user-managed replication.
    ///
    /// Only populated if the parent
    /// [Secret][google.cloud.secretmanager.v1.Secret] has a user-managed
    /// replication policy.
    ///
    /// [google.cloud.secretmanager.v1.Secret]: <doc:Secret>
    /// [google.cloud.secretmanager.v1.SecretVersion]: <doc:SecretVersion>
    indirect case userManaged(ReplicationStatus.UserManagedStatus?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.secretmanager.v1.ReplicationStatus"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
