// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// The replication status of a
/// [SecretVersion][google.cloud.secretmanager.v1.SecretVersion].
///
/// [google.cloud.secretmanager.v1.SecretVersion]: <doc:SecretVersion>
public struct ReplicationStatus: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The replication status of the
  /// [SecretVersion][google.cloud.secretmanager.v1.SecretVersion].
  ///
  /// [google.cloud.secretmanager.v1.SecretVersion]: <doc:SecretVersion>
  public var replicationStatus: OneOf_ReplicationStatus?

  /// Initialize a new instance of `ReplicationStatus`.
  public init(
    replicationStatus: OneOf_ReplicationStatus? = nil,
  ) {
    self.replicationStatus = replicationStatus
  }

  private enum CodingKeys: String, CodingKey {
    case automatic = "automatic"
    case userManaged = "userManaged"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var replicationStatus: OneOf_ReplicationStatus? = nil
    let replicationStatusCheckAndSet = {
      if replicationStatus != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'replicationStatus'"))
      }
      replicationStatus = $0
    }
    if let automatic = try container.decodeIfPresent(
      ReplicationStatus.AutomaticStatus?.self, forKey: .automatic)
    {
      try replicationStatusCheckAndSet(.automatic(automatic))
    }
    if let userManaged = try container.decodeIfPresent(
      ReplicationStatus.UserManagedStatus?.self, forKey: .userManaged)
    {
      try replicationStatusCheckAndSet(.userManaged(userManaged))
    }
    self.replicationStatus = replicationStatus
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.replicationStatus {
      switch choice {
      case .automatic(let value):
        try container.encode(value, forKey: .automatic)
      case .userManaged(let value):
        try container.encode(value, forKey: .userManaged)
      }
    }
  }

  /// The replication status of a
  /// [SecretVersion][google.cloud.secretmanager.v1.SecretVersion] using
  /// automatic replication.
  ///
  /// Only populated if the parent [Secret][google.cloud.secretmanager.v1.Secret]
  /// has an automatic replication policy.
  ///
  /// [google.cloud.secretmanager.v1.Secret]: <doc:Secret>
  /// [google.cloud.secretmanager.v1.SecretVersion]: <doc:SecretVersion>
  public struct AutomaticStatus: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Output only. The customer-managed encryption status of the
    /// [SecretVersion][google.cloud.secretmanager.v1.SecretVersion]. Only
    /// populated if customer-managed encryption is used.
    ///
    /// [google.cloud.secretmanager.v1.SecretVersion]: <doc:SecretVersion>
    public var customerManagedEncryption: CustomerManagedEncryptionStatus?

    /// Initialize a new instance of `AutomaticStatus`.
    public init(
      customerManagedEncryption: CustomerManagedEncryptionStatus? = nil,
    ) {
      self.customerManagedEncryption = customerManagedEncryption
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.cloud.secretmanager.v1.ReplicationStatus.AutomaticStatus"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// The replication status of a
  /// [SecretVersion][google.cloud.secretmanager.v1.SecretVersion] using
  /// user-managed replication.
  ///
  /// Only populated if the parent [Secret][google.cloud.secretmanager.v1.Secret]
  /// has a user-managed replication policy.
  ///
  /// [google.cloud.secretmanager.v1.Secret]: <doc:Secret>
  /// [google.cloud.secretmanager.v1.SecretVersion]: <doc:SecretVersion>
  public struct UserManagedStatus: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Output only. The list of replica statuses for the
    /// [SecretVersion][google.cloud.secretmanager.v1.SecretVersion].
    ///
    /// [google.cloud.secretmanager.v1.SecretVersion]: <doc:SecretVersion>
    public var replicas: [ReplicationStatus.UserManagedStatus.ReplicaStatus]

    /// Initialize a new instance of `UserManagedStatus`.
    public init(
      replicas: [ReplicationStatus.UserManagedStatus.ReplicaStatus] = [],
    ) {
      self.replicas = replicas
    }

    /// Describes the status of a user-managed replica for the
    /// [SecretVersion][google.cloud.secretmanager.v1.SecretVersion].
    ///
    /// [google.cloud.secretmanager.v1.SecretVersion]: <doc:SecretVersion>
    public struct ReplicaStatus: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      /// Output only. The canonical ID of the replica location.
      /// For example: `"us-east1"`.
      public var location: Swift.String

      /// Output only. The customer-managed encryption status of the
      /// [SecretVersion][google.cloud.secretmanager.v1.SecretVersion]. Only
      /// populated if customer-managed encryption is used.
      ///
      /// [google.cloud.secretmanager.v1.SecretVersion]: <doc:SecretVersion>
      public var customerManagedEncryption: CustomerManagedEncryptionStatus?

      /// Initialize a new instance of `ReplicaStatus`.
      public init(
        location: Swift.String = Swift.String(),
        customerManagedEncryption: CustomerManagedEncryptionStatus? = nil,
      ) {
        self.location = location
        self.customerManagedEncryption = customerManagedEncryption
      }

      public static var _anyTypeUrl: String {
        return
          "type.googleapis.com/google.cloud.secretmanager.v1.ReplicationStatus.UserManagedStatus.ReplicaStatus"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.cloud.secretmanager.v1.ReplicationStatus.UserManagedStatus"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// The replication status of the
  /// [SecretVersion][google.cloud.secretmanager.v1.SecretVersion].
  ///
  /// [google.cloud.secretmanager.v1.SecretVersion]: <doc:SecretVersion>
  public enum OneOf_ReplicationStatus: Codable, Equatable, Sendable {
    /// Describes the replication status of a
    /// [SecretVersion][google.cloud.secretmanager.v1.SecretVersion] with
    /// automatic replication.
    ///
    /// Only populated if the parent
    /// [Secret][google.cloud.secretmanager.v1.Secret] has an automatic
    /// replication policy.
    ///
    /// [google.cloud.secretmanager.v1.Secret]: <doc:Secret>
    /// [google.cloud.secretmanager.v1.SecretVersion]: <doc:SecretVersion>
    indirect case automatic(ReplicationStatus.AutomaticStatus?)
    /// Describes the replication status of a
    /// [SecretVersion][google.cloud.secretmanager.v1.SecretVersion] with
    /// user-managed replication.
    ///
    /// Only populated if the parent
    /// [Secret][google.cloud.secretmanager.v1.Secret] has a user-managed
    /// replication policy.
    ///
    /// [google.cloud.secretmanager.v1.Secret]: <doc:Secret>
    /// [google.cloud.secretmanager.v1.SecretVersion]: <doc:SecretVersion>
    indirect case userManaged(ReplicationStatus.UserManagedStatus?)
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.secretmanager.v1.ReplicationStatus"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
