// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

import GoogleCloudLocation
import GoogleCloudWkt
import GoogleIamV1

/// The rotation time and period for a
/// [Secret][google.cloud.secretmanager.v1.Secret]. At next_rotation_time, Secret
/// Manager will send a Pub/Sub notification to the topics configured on the
/// Secret. [Secret.topics][google.cloud.secretmanager.v1.Secret.topics] must be
/// set to configure rotation.
///
/// [google.cloud.secretmanager.v1.Secret]: <doc:Secret>
/// [google.cloud.secretmanager.v1.Secret.topics]: <doc:Secret/topics>
public struct Rotation: Codable, Equatable, GoogleCloudWkt._AnyPackable, Sendable {
  /// Optional. Timestamp in UTC at which the
  /// [Secret][google.cloud.secretmanager.v1.Secret] is scheduled to rotate.
  /// Cannot be set to less than 300s (5 min) in the future and at most
  /// 3153600000s (100 years).
  ///
  /// [next_rotation_time][google.cloud.secretmanager.v1.Rotation.next_rotation_time]
  /// MUST  be set if
  /// [rotation_period][google.cloud.secretmanager.v1.Rotation.rotation_period]
  /// is set.
  ///
  /// [google.cloud.secretmanager.v1.Rotation.next_rotation_time]: <doc:Rotation/nextRotationTime>
  /// [google.cloud.secretmanager.v1.Rotation.rotation_period]: <doc:Rotation/rotationPeriod>
  /// [google.cloud.secretmanager.v1.Secret]: <doc:Secret>
  public var nextRotationTime: GoogleCloudWkt.Timestamp?

  /// Input only. The Duration between rotation notifications. Must be in seconds
  /// and at least 3600s (1h) and at most 3153600000s (100 years).
  ///
  /// If
  /// [rotation_period][google.cloud.secretmanager.v1.Rotation.rotation_period]
  /// is set,
  /// [next_rotation_time][google.cloud.secretmanager.v1.Rotation.next_rotation_time]
  /// must be set.
  /// [next_rotation_time][google.cloud.secretmanager.v1.Rotation.next_rotation_time]
  /// will be advanced by this period when the service automatically sends
  /// rotation notifications.
  ///
  /// [google.cloud.secretmanager.v1.Rotation.next_rotation_time]: <doc:Rotation/nextRotationTime>
  /// [google.cloud.secretmanager.v1.Rotation.rotation_period]: <doc:Rotation/rotationPeriod>
  public var rotationPeriod: GoogleCloudWkt.Duration?

  /// Initialize a new instance of `Rotation`.
  public init(
    nextRotationTime: GoogleCloudWkt.Timestamp? = nil,
    rotationPeriod: GoogleCloudWkt.Duration? = nil,
  ) {
    self.nextRotationTime = nextRotationTime
    self.rotationPeriod = rotationPeriod
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.secretmanager.v1.Rotation"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
