// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudLocation
import GoogleIAMV1
import GoogleWKT
import GoogleGax

extension Clients {
  protocol SecretManagerServiceStub: Sendable {
    func listSecrets(
      request: ListSecretsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecretManagerV1.ListSecretsResponse

    func createSecret(
      request: CreateSecretRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecretManagerV1.Secret

    func addSecretVersion(
      request: AddSecretVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecretManagerV1.SecretVersion

    func getSecret(
      request: GetSecretRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecretManagerV1.Secret

    func updateSecret(
      request: UpdateSecretRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecretManagerV1.Secret

    func deleteSecret(
      request: DeleteSecretRequest, options: GoogleGax.RequestOptions
    ) async throws

    func listSecretVersions(
      request: ListSecretVersionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecretManagerV1.ListSecretVersionsResponse

    func getSecretVersion(
      request: GetSecretVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecretManagerV1.SecretVersion

    func accessSecretVersion(
      request: AccessSecretVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecretManagerV1.AccessSecretVersionResponse

    func disableSecretVersion(
      request: DisableSecretVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecretManagerV1.SecretVersion

    func enableSecretVersion(
      request: EnableSecretVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecretManagerV1.SecretVersion

    func destroySecretVersion(
      request: DestroySecretVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecretManagerV1.SecretVersion

    func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy

    func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse

    func enableManagedRotation(
      request: EnableManagedRotationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecretManagerV1.SecretVersion

    func rotateSecret(
      request: RotateSecretRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecretManagerV1.SecretVersion

    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location
  }
}
