// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

import GoogleCloudLocation
import GoogleCloudWkt
import GoogleIamV1

/// A [Secret][google.cloud.secretmanager.v1.Secret] is a logical secret whose
/// value and versions can be accessed.
///
/// A [Secret][google.cloud.secretmanager.v1.Secret] is made up of zero or more
/// [SecretVersions][google.cloud.secretmanager.v1.SecretVersion] that represent
/// the secret data.
public struct Secret: Codable, Equatable, GoogleCloudWkt._AnyPackable {
  /// Output only. The resource name of the
  /// [Secret][google.cloud.secretmanager.v1.Secret] in the format
  /// `projects/*/secrets/*`.
  public var name: String

  /// Optional. Immutable. The replication policy of the secret data attached to
  /// the [Secret][google.cloud.secretmanager.v1.Secret].
  ///
  /// The replication policy cannot be changed after the Secret has been created.
  public var replication: Replication?

  /// Output only. The time at which the
  /// [Secret][google.cloud.secretmanager.v1.Secret] was created.
  public var createTime: GoogleCloudWkt.Timestamp?

  /// The labels assigned to this Secret.
  ///
  /// Label keys must be between 1 and 63 characters long, have a UTF-8 encoding
  /// of maximum 128 bytes, and must conform to the following PCRE regular
  /// expression: `[\p{Ll}\p{Lo}][\p{Ll}\p{Lo}\p{N}_-]{0,62}`
  ///
  /// Label values must be between 0 and 63 characters long, have a UTF-8
  /// encoding of maximum 128 bytes, and must conform to the following PCRE
  /// regular expression: `[\p{Ll}\p{Lo}\p{N}_-]{0,63}`
  ///
  /// No more than 64 labels can be assigned to a given resource.
  public var labels: [String: String]

  /// Optional. A list of up to 10 Pub/Sub topics to which messages are published
  /// when control plane operations are called on the secret or its versions.
  public var topics: [Topic]

  /// Optional. Etag of the currently stored
  /// [Secret][google.cloud.secretmanager.v1.Secret].
  public var etag: String

  /// Optional. Rotation policy attached to the
  /// [Secret][google.cloud.secretmanager.v1.Secret]. May be excluded if there is
  /// no rotation policy.
  public var rotation: Rotation?

  /// Optional. Mapping from version alias to version name.
  ///
  /// A version alias is a string with a maximum length of 63 characters and can
  /// contain uppercase and lowercase letters, numerals, and the hyphen (`-`)
  /// and underscore ('_') characters. An alias string must start with a
  /// letter and cannot be the string 'latest' or 'NEW'.
  /// No more than 50 aliases can be assigned to a given secret.
  ///
  /// Version-Alias pairs will be viewable via GetSecret and modifiable via
  /// UpdateSecret. Access by alias is only be supported on
  /// GetSecretVersion and AccessSecretVersion.
  public var versionAliases: [String: Int64]

  /// Optional. Custom metadata about the secret.
  ///
  /// Annotations are distinct from various forms of labels.
  /// Annotations exist to allow client tools to store their own state
  /// information without requiring a database.
  ///
  /// Annotation keys must be between 1 and 63 characters long, have a UTF-8
  /// encoding of maximum 128 bytes, begin and end with an alphanumeric character
  /// ([a-z0-9A-Z]), and may have dashes (-), underscores (_), dots (.), and
  /// alphanumerics in between these symbols.
  ///
  /// The total size of annotation keys and values must be less than 16KiB.
  public var annotations: [String: String]

  /// Optional. Secret Version TTL after destruction request
  ///
  /// This is a part of the Delayed secret version destroy feature.
  /// For secret with TTL>0, version destruction doesn't happen immediately
  /// on calling destroy instead the version goes to a disabled state and
  /// destruction happens after the TTL expires.
  public var versionDestroyTtl: GoogleCloudWkt.Duration?

  /// Optional. The customer-managed encryption configuration of the regionalized
  /// secrets. If no configuration is provided, Google-managed default encryption
  /// is used.
  ///
  /// Updates to the [Secret][google.cloud.secretmanager.v1.Secret] encryption
  /// configuration only apply to
  /// [SecretVersions][google.cloud.secretmanager.v1.SecretVersion] added
  /// afterwards. They do not apply retroactively to existing
  /// [SecretVersions][google.cloud.secretmanager.v1.SecretVersion].
  public var customerManagedEncryption: CustomerManagedEncryption?

  /// Optional. Input only. Immutable. Mapping of Tag keys/values directly bound
  /// to this resource. For example:
  ///   "123/environment": "production",
  ///   "123/costCenter": "marketing"
  ///
  /// Tags are used to organize and group resources.
  ///
  /// Tags can be used to control policy evaluation for the resource.
  public var tags: [String: String]

  /// Expiration policy attached to the
  /// [Secret][google.cloud.secretmanager.v1.Secret]. If specified the
  /// [Secret][google.cloud.secretmanager.v1.Secret] and all
  /// [SecretVersions][google.cloud.secretmanager.v1.SecretVersion] will be
  /// automatically deleted at expiration. Expired secrets are irreversibly
  /// deleted.
  ///
  /// Expiration is *not* the recommended way to set time-based permissions. [IAM
  /// Conditions](https://cloud.google.com/secret-manager/docs/access-control#conditions)
  /// is recommended for granting time-based permissions because the operation
  /// can be reversed.
  public var expiration: OneOf_Expiration?

  /// Initialize a new instance of `Secret`.
  public init(
    name: String = String(),
    replication: Replication? = nil,
    createTime: GoogleCloudWkt.Timestamp? = nil,
    labels: [String: String] = [:],
    topics: [Topic] = [],
    etag: String = String(),
    rotation: Rotation? = nil,
    versionAliases: [String: Int64] = [:],
    annotations: [String: String] = [:],
    versionDestroyTtl: GoogleCloudWkt.Duration? = nil,
    customerManagedEncryption: CustomerManagedEncryption? = nil,
    tags: [String: String] = [:],
    expiration: OneOf_Expiration? = nil,
  ) {
    self.name = name
    self.replication = replication
    self.createTime = createTime
    self.labels = labels
    self.topics = topics
    self.etag = etag
    self.rotation = rotation
    self.versionAliases = versionAliases
    self.annotations = annotations
    self.versionDestroyTtl = versionDestroyTtl
    self.customerManagedEncryption = customerManagedEncryption
    self.tags = tags
    self.expiration = expiration
  }

  /// Expiration policy attached to the
  /// [Secret][google.cloud.secretmanager.v1.Secret]. If specified the
  /// [Secret][google.cloud.secretmanager.v1.Secret] and all
  /// [SecretVersions][google.cloud.secretmanager.v1.SecretVersion] will be
  /// automatically deleted at expiration. Expired secrets are irreversibly
  /// deleted.
  ///
  /// Expiration is *not* the recommended way to set time-based permissions. [IAM
  /// Conditions](https://cloud.google.com/secret-manager/docs/access-control#conditions)
  /// is recommended for granting time-based permissions because the operation
  /// can be reversed.
  public enum OneOf_Expiration: Codable, Equatable {
    /// Optional. Timestamp in UTC when the
    /// [Secret][google.cloud.secretmanager.v1.Secret] is scheduled to expire.
    /// This is always provided on output, regardless of what was sent on input.
    indirect case expireTime(GoogleCloudWkt.Timestamp?)
    /// Input only. The TTL for the
    /// [Secret][google.cloud.secretmanager.v1.Secret].
    indirect case ttl(GoogleCloudWkt.Duration?)
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.secretmanager.v1.Secret"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
