// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

import GoogleCloudLocation
import GoogleCloudWkt
import GoogleIamV1

/// A secret version resource in the Secret Manager API.
public struct SecretVersion: Codable, Equatable, GoogleCloudWkt._AnyPackable {
  /// Output only. The resource name of the
  /// [SecretVersion][google.cloud.secretmanager.v1.SecretVersion] in the format
  /// `projects/*/secrets/*/versions/*`.
  ///
  /// [SecretVersion][google.cloud.secretmanager.v1.SecretVersion] IDs in a
  /// [Secret][google.cloud.secretmanager.v1.Secret] start at 1 and are
  /// incremented for each subsequent version of the secret.
  public var name: String

  /// Output only. The time at which the
  /// [SecretVersion][google.cloud.secretmanager.v1.SecretVersion] was created.
  public var createTime: GoogleCloudWkt.Timestamp?

  /// Output only. The time this
  /// [SecretVersion][google.cloud.secretmanager.v1.SecretVersion] was destroyed.
  /// Only present if [state][google.cloud.secretmanager.v1.SecretVersion.state]
  /// is
  /// [DESTROYED][google.cloud.secretmanager.v1.SecretVersion.State.DESTROYED].
  public var destroyTime: GoogleCloudWkt.Timestamp?

  /// Output only. The current state of the
  /// [SecretVersion][google.cloud.secretmanager.v1.SecretVersion].
  public var state: SecretVersion.State

  /// The replication status of the
  /// [SecretVersion][google.cloud.secretmanager.v1.SecretVersion].
  public var replicationStatus: ReplicationStatus?

  /// Output only. Etag of the currently stored
  /// [SecretVersion][google.cloud.secretmanager.v1.SecretVersion].
  public var etag: String

  /// Output only. True if payload checksum specified in
  /// [SecretPayload][google.cloud.secretmanager.v1.SecretPayload] object has
  /// been received by
  /// [SecretManagerService][google.cloud.secretmanager.v1.SecretManagerService]
  /// on
  /// [SecretManagerService.AddSecretVersion][google.cloud.secretmanager.v1.SecretManagerService.AddSecretVersion].
  public var clientSpecifiedPayloadChecksum: Bool

  /// Optional. Output only. Scheduled destroy time for secret version.
  /// This is a part of the Delayed secret version destroy feature. For a
  /// Secret with a valid version destroy TTL, when a secert version is
  /// destroyed, version is moved to disabled state and it is scheduled for
  /// destruction Version is destroyed only after the scheduled_destroy_time.
  public var scheduledDestroyTime: GoogleCloudWkt.Timestamp?

  /// Output only. The customer-managed encryption status of the
  /// [SecretVersion][google.cloud.secretmanager.v1.SecretVersion]. Only
  /// populated if customer-managed encryption is used and
  /// [Secret][google.cloud.secretmanager.v1.Secret] is a regionalized secret.
  public var customerManagedEncryption: CustomerManagedEncryptionStatus?

  /// Initialize a new instance of `SecretVersion`.
  public init(
    name: String = String(),
    createTime: GoogleCloudWkt.Timestamp? = nil,
    destroyTime: GoogleCloudWkt.Timestamp? = nil,
    state: SecretVersion.State = SecretVersion.State(),
    replicationStatus: ReplicationStatus? = nil,
    etag: String = String(),
    clientSpecifiedPayloadChecksum: Bool = Bool(),
    scheduledDestroyTime: GoogleCloudWkt.Timestamp? = nil,
    customerManagedEncryption: CustomerManagedEncryptionStatus? = nil,
  ) {
    self.name = name
    self.createTime = createTime
    self.destroyTime = destroyTime
    self.state = state
    self.replicationStatus = replicationStatus
    self.etag = etag
    self.clientSpecifiedPayloadChecksum = clientSpecifiedPayloadChecksum
    self.scheduledDestroyTime = scheduledDestroyTime
    self.customerManagedEncryption = customerManagedEncryption
  }

  /// The state of a
  /// [SecretVersion][google.cloud.secretmanager.v1.SecretVersion], indicating if
  /// it can be accessed.
  public enum State: Int, Codable, Equatable {
    case unspecified = 0
    case enabled = 1
    case disabled = 2
    case destroyed = 3

    public init() {
      self = .unspecified
    }

    public var stringValue: String {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .enabled: return "ENABLED"
      case .disabled: return "DISABLED"
      case .destroyed: return "DESTROYED"
      }
    }

    public init?(stringValue: String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "ENABLED": self = .enabled
      case "DISABLED": self = .disabled
      case "DESTROYED": self = .destroyed
      default: return nil
      }
    }
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.secretmanager.v1.SecretVersion"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
