// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// A [Secret][google.cloud.secretmanager.v1.Secret] is a logical secret whose
/// value and versions can be accessed.
///
/// A [Secret][google.cloud.secretmanager.v1.Secret] is made up of zero or more
/// [SecretVersions][google.cloud.secretmanager.v1.SecretVersion] that represent
/// the secret data.
///
/// [google.cloud.secretmanager.v1.Secret]: <doc:Secret>
/// [google.cloud.secretmanager.v1.SecretVersion]: <doc:SecretVersion>
public struct Secret: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. The resource name of the
  /// [Secret][google.cloud.secretmanager.v1.Secret] in the format
  /// `projects/*/secrets/*`.
  ///
  /// [google.cloud.secretmanager.v1.Secret]: <doc:Secret>
  public var name: Swift.String = Swift.String()

  /// Optional. Immutable. The replication policy of the secret data attached to
  /// the [Secret][google.cloud.secretmanager.v1.Secret].
  ///
  /// The replication policy cannot be changed after the Secret has been created.
  ///
  /// [google.cloud.secretmanager.v1.Secret]: <doc:Secret>
  public var replication: Replication? = nil

  /// Output only. The time at which the
  /// [Secret][google.cloud.secretmanager.v1.Secret] was created.
  ///
  /// [google.cloud.secretmanager.v1.Secret]: <doc:Secret>
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// The labels assigned to this Secret.
  ///
  /// Label keys must be between 1 and 63 characters long, have a UTF-8 encoding
  /// of maximum 128 bytes, and must conform to the following PCRE regular
  /// expression: `[\p{Ll}\p{Lo}][\p{Ll}\p{Lo}\p{N}_-]{0,62}`
  ///
  /// Label values must be between 0 and 63 characters long, have a UTF-8
  /// encoding of maximum 128 bytes, and must conform to the following PCRE
  /// regular expression: `[\p{Ll}\p{Lo}\p{N}_-]{0,63}`
  ///
  /// No more than 64 labels can be assigned to a given resource.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Optional. A list of up to 10 Pub/Sub topics to which messages are published
  /// when control plane operations are called on the secret or its versions.
  public var topics: [Topic] = []

  /// Optional. Etag of the currently stored
  /// [Secret][google.cloud.secretmanager.v1.Secret].
  ///
  /// [google.cloud.secretmanager.v1.Secret]: <doc:Secret>
  public var etag: Swift.String = Swift.String()

  /// Optional. Rotation policy attached to the
  /// [Secret][google.cloud.secretmanager.v1.Secret]. May be excluded if there is
  /// no rotation policy.
  ///
  /// [google.cloud.secretmanager.v1.Secret]: <doc:Secret>
  public var rotation: Rotation? = nil

  /// Optional. Mapping from version alias to version name.
  ///
  /// A version alias is a string with a maximum length of 63 characters and can
  /// contain uppercase and lowercase letters, numerals, and the hyphen (`-`)
  /// and underscore ('_') characters. An alias string must start with a
  /// letter and cannot be the string 'latest' or 'NEW'.
  /// No more than 50 aliases can be assigned to a given secret.
  ///
  /// Version-Alias pairs will be viewable via GetSecret and modifiable via
  /// UpdateSecret. Access by alias is only be supported on
  /// GetSecretVersion and AccessSecretVersion.
  public var versionAliases: [Swift.String: Swift.Int64] = [:]

  /// Optional. Custom metadata about the secret.
  ///
  /// Annotations are distinct from various forms of labels.
  /// Annotations exist to allow client tools to store their own state
  /// information without requiring a database.
  ///
  /// Annotation keys must be between 1 and 63 characters long, have a UTF-8
  /// encoding of maximum 128 bytes, begin and end with an alphanumeric character
  /// ([a-z0-9A-Z]), and may have dashes (-), underscores (_), dots (.), and
  /// alphanumerics in between these symbols.
  ///
  /// The total size of annotation keys and values must be less than 16KiB.
  public var annotations: [Swift.String: Swift.String] = [:]

  /// Optional. Secret Version TTL after destruction request
  ///
  /// This is a part of the Delayed secret version destroy feature.
  /// For secret with TTL>0, version destruction doesn't happen immediately
  /// on calling destroy instead the version goes to a disabled state and
  /// destruction happens after the TTL expires.
  public var versionDestroyTtl: GoogleCloudWkt.Duration? = nil

  /// Optional. The customer-managed encryption configuration of the regionalized
  /// secrets. If no configuration is provided, Google-managed default encryption
  /// is used.
  ///
  /// Updates to the [Secret][google.cloud.secretmanager.v1.Secret] encryption
  /// configuration only apply to
  /// [SecretVersions][google.cloud.secretmanager.v1.SecretVersion] added
  /// afterwards. They do not apply retroactively to existing
  /// [SecretVersions][google.cloud.secretmanager.v1.SecretVersion].
  ///
  /// [google.cloud.secretmanager.v1.Secret]: <doc:Secret>
  /// [google.cloud.secretmanager.v1.SecretVersion]: <doc:SecretVersion>
  public var customerManagedEncryption: CustomerManagedEncryption? = nil

  /// Optional. Input only. Immutable. Mapping of Tag keys/values directly bound
  /// to this resource. For example:
  ///   "123/environment": "production",
  ///   "123/costCenter": "marketing"
  ///
  /// Tags are used to organize and group resources.
  ///
  /// Tags can be used to control policy evaluation for the resource.
  public var tags: [Swift.String: Swift.String] = [:]

  /// Expiration policy attached to the
  /// [Secret][google.cloud.secretmanager.v1.Secret]. If specified the
  /// [Secret][google.cloud.secretmanager.v1.Secret] and all
  /// [SecretVersions][google.cloud.secretmanager.v1.SecretVersion] will be
  /// automatically deleted at expiration. Expired secrets are irreversibly
  /// deleted.
  ///
  /// Expiration is *not* the recommended way to set time-based permissions. [IAM
  /// Conditions](https://cloud.google.com/secret-manager/docs/access-control#conditions)
  /// is recommended for granting time-based permissions because the operation
  /// can be reversed.
  ///
  /// [google.cloud.secretmanager.v1.Secret]: <doc:Secret>
  /// [google.cloud.secretmanager.v1.SecretVersion]: <doc:SecretVersion>
  public var expiration: OneOf_Expiration? = nil

  /// Initialize a new instance of `Secret`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Secret().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: String, CodingKey {
    case name = "name"
    case replication = "replication"
    case createTime = "createTime"
    case labels = "labels"
    case topics = "topics"
    case expireTime = "expireTime"
    case ttl = "ttl"
    case etag = "etag"
    case rotation = "rotation"
    case versionAliases = "versionAliases"
    case annotations = "annotations"
    case versionDestroyTtl = "versionDestroyTtl"
    case customerManagedEncryption = "customerManagedEncryption"
    case tags = "tags"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.name = try container.decode(Swift.String.self, forKey: .name)
    self.replication = try container.decodeIfPresent(Replication.self, forKey: .replication)
    self.createTime = try container.decodeIfPresent(
      GoogleCloudWkt.Timestamp.self, forKey: .createTime)
    self.labels = try container.decode([Swift.String: Swift.String].self, forKey: .labels)
    self.topics = try container.decode([Topic].self, forKey: .topics)
    self.etag = try container.decode(Swift.String.self, forKey: .etag)
    self.rotation = try container.decodeIfPresent(Rotation.self, forKey: .rotation)
    self.versionAliases = try container.decode(
      [Swift.String: Swift.Int64].self, forKey: .versionAliases)
    self.annotations = try container.decode([Swift.String: Swift.String].self, forKey: .annotations)
    self.versionDestroyTtl = try container.decodeIfPresent(
      GoogleCloudWkt.Duration.self, forKey: .versionDestroyTtl)
    self.customerManagedEncryption = try container.decodeIfPresent(
      CustomerManagedEncryption.self, forKey: .customerManagedEncryption)
    self.tags = try container.decode([Swift.String: Swift.String].self, forKey: .tags)

    var expiration: OneOf_Expiration? = nil
    let expirationCheckAndSet = {
      if expiration != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'expiration'"))
      }
      expiration = $0
    }
    if let expireTime = try container.decodeIfPresent(
      GoogleCloudWkt.Timestamp?.self, forKey: .expireTime)
    {
      try expirationCheckAndSet(.expireTime(expireTime))
    }
    if let ttl = try container.decodeIfPresent(GoogleCloudWkt.Duration?.self, forKey: .ttl) {
      try expirationCheckAndSet(.ttl(ttl))
    }
    self.expiration = expiration
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.replication, forKey: .replication)
    try container.encode(self.createTime, forKey: .createTime)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.topics, forKey: .topics)
    try container.encode(self.etag, forKey: .etag)
    try container.encode(self.rotation, forKey: .rotation)
    try container.encode(self.versionAliases, forKey: .versionAliases)
    try container.encode(self.annotations, forKey: .annotations)
    try container.encode(self.versionDestroyTtl, forKey: .versionDestroyTtl)
    try container.encode(self.customerManagedEncryption, forKey: .customerManagedEncryption)
    try container.encode(self.tags, forKey: .tags)

    if let choice = self.expiration {
      switch choice {
      case .expireTime(let value):
        try container.encode(value, forKey: .expireTime)
      case .ttl(let value):
        try container.encode(value, forKey: .ttl)
      }
    }
  }

  /// Expiration policy attached to the
  /// [Secret][google.cloud.secretmanager.v1.Secret]. If specified the
  /// [Secret][google.cloud.secretmanager.v1.Secret] and all
  /// [SecretVersions][google.cloud.secretmanager.v1.SecretVersion] will be
  /// automatically deleted at expiration. Expired secrets are irreversibly
  /// deleted.
  ///
  /// Expiration is *not* the recommended way to set time-based permissions. [IAM
  /// Conditions](https://cloud.google.com/secret-manager/docs/access-control#conditions)
  /// is recommended for granting time-based permissions because the operation
  /// can be reversed.
  ///
  /// [google.cloud.secretmanager.v1.Secret]: <doc:Secret>
  /// [google.cloud.secretmanager.v1.SecretVersion]: <doc:SecretVersion>
  public enum OneOf_Expiration: Codable, Equatable, Sendable {
    /// Optional. Timestamp in UTC when the
    /// [Secret][google.cloud.secretmanager.v1.Secret] is scheduled to expire.
    /// This is always provided on output, regardless of what was sent on input.
    ///
    /// [google.cloud.secretmanager.v1.Secret]: <doc:Secret>
    indirect case expireTime(GoogleCloudWkt.Timestamp?)
    /// Input only. The TTL for the
    /// [Secret][google.cloud.secretmanager.v1.Secret].
    ///
    /// [google.cloud.secretmanager.v1.Secret]: <doc:Secret>
    indirect case ttl(GoogleCloudWkt.Duration?)
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.secretmanager.v1.Secret"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
