// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif

import GoogleCloudAuth
import GoogleCloudGax

import GoogleCloudLocation
import GoogleCloudWkt
import GoogleIamV1

/// Secret Manager Service
///
/// Manages secrets and operations using those secrets. Implements a REST
/// model with the following objects:
///
/// * [Secret][google.cloud.secretmanager.v1.Secret]
/// * [SecretVersion][google.cloud.secretmanager.v1.SecretVersion]
///
/// @Snippet(path: "SecretManagerServiceQuickstart")
public class SecretManagerService {
  let inner: GoogleCloudGax.HTTPClient

  /// Creates a new `SecretManagerService` instance.
  public init(
    endpoint: String? = nil,
    credentials: GoogleCloudAuth.Credentials? = nil,
    session: URLSession? = nil,
  ) throws {
    let endpoint = endpoint ?? "https://secretmanager.googleapis.com"
    self.inner = try HTTPClient(endpoint: endpoint, credentials: credentials, session: session)
  }

  /// Lists [Secrets][google.cloud.secretmanager.v1.Secret].
  ///
  /// @Snippet(path: "SecretManagerService_ListSecrets")
  public func listSecrets(request: ListSecretsRequest) async throws
    -> ListSecretsResponse
  {
    let path = try { () throws -> String in
      guard let pathVariable0 = request.parent as String?, !pathVariable0.isEmpty else {
        throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
      }
      return "/v1/\(pathVariable0)/secrets"
    }()
    var query = [URLQueryItem(name: "$alt", value: "json;enum-encoding=int")]
    let encoder = GoogleCloudGax.QueryParameterEncoder()
    query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
    query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
    query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
    var req = try await self.inner.Request(path: path, query: query)
    req.httpMethod = "GET"
    let (data, response) = try await self.inner.data(for: req)
    if !(200..<300).contains(response.statusCode) {
      throw RequestError.http(
        HTTPDetails(
          http_status_code: response.statusCode,
          headers: [:],
          payload: data,
        ))
    }
    return try ProtoJSONDecoder().decode(ListSecretsResponse.self, from: data)
  }

  /// Creates a new [Secret][google.cloud.secretmanager.v1.Secret] containing no
  /// [SecretVersions][google.cloud.secretmanager.v1.SecretVersion].
  ///
  /// @Snippet(path: "SecretManagerService_CreateSecret")
  public func createSecret(request: CreateSecretRequest) async throws
    -> Secret
  {
    let path = try { () throws -> String in
      guard let pathVariable0 = request.parent as String?, !pathVariable0.isEmpty else {
        throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
      }
      return "/v1/\(pathVariable0)/secrets"
    }()
    var query = [URLQueryItem(name: "$alt", value: "json;enum-encoding=int")]
    let encoder = GoogleCloudGax.QueryParameterEncoder()
    query.append(contentsOf: try encoder.encode(request.secretId, prefix: "secretId"))
    var req = try await self.inner.Request(path: path, query: query)
    req.httpMethod = "POST"
    if let body = request.secret {
      req.setValue("application/json", forHTTPHeaderField: "Content-Type")
      req.httpBody = try JSONEncoder().encode(body)
    }
    let (data, response) = try await self.inner.data(for: req)
    if !(200..<300).contains(response.statusCode) {
      throw RequestError.http(
        HTTPDetails(
          http_status_code: response.statusCode,
          headers: [:],
          payload: data,
        ))
    }
    return try ProtoJSONDecoder().decode(Secret.self, from: data)
  }

  /// Creates a new [SecretVersion][google.cloud.secretmanager.v1.SecretVersion]
  /// containing secret data and attaches it to an existing
  /// [Secret][google.cloud.secretmanager.v1.Secret].
  ///
  /// @Snippet(path: "SecretManagerService_AddSecretVersion")
  public func addSecretVersion(request: AddSecretVersionRequest) async throws
    -> SecretVersion
  {
    let path = try { () throws -> String in
      guard let pathVariable0 = request.parent as String?, !pathVariable0.isEmpty else {
        throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
      }
      return "/v1/\(pathVariable0):addVersion"
    }()
    let query = [URLQueryItem(name: "$alt", value: "json;enum-encoding=int")]
    var req = try await self.inner.Request(path: path, query: query)
    req.httpMethod = "POST"
    req.setValue("application/json", forHTTPHeaderField: "Content-Type")
    req.httpBody = try JSONEncoder().encode(request)
    let (data, response) = try await self.inner.data(for: req)
    if !(200..<300).contains(response.statusCode) {
      throw RequestError.http(
        HTTPDetails(
          http_status_code: response.statusCode,
          headers: [:],
          payload: data,
        ))
    }
    return try ProtoJSONDecoder().decode(SecretVersion.self, from: data)
  }

  /// Gets metadata for a given [Secret][google.cloud.secretmanager.v1.Secret].
  ///
  /// @Snippet(path: "SecretManagerService_GetSecret")
  public func getSecret(request: GetSecretRequest) async throws
    -> Secret
  {
    let path = try { () throws -> String in
      guard let pathVariable0 = request.name as String?, !pathVariable0.isEmpty else {
        throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
      }
      return "/v1/\(pathVariable0)"
    }()
    let query = [URLQueryItem(name: "$alt", value: "json;enum-encoding=int")]
    var req = try await self.inner.Request(path: path, query: query)
    req.httpMethod = "GET"
    let (data, response) = try await self.inner.data(for: req)
    if !(200..<300).contains(response.statusCode) {
      throw RequestError.http(
        HTTPDetails(
          http_status_code: response.statusCode,
          headers: [:],
          payload: data,
        ))
    }
    return try ProtoJSONDecoder().decode(Secret.self, from: data)
  }

  /// Updates metadata of an existing
  /// [Secret][google.cloud.secretmanager.v1.Secret].
  ///
  /// @Snippet(path: "SecretManagerService_UpdateSecret")
  public func updateSecret(request: UpdateSecretRequest) async throws
    -> Secret
  {
    let path = try { () throws -> String in
      guard let pathVariable0 = request.secret.map({ $0.name }), !pathVariable0.isEmpty else {
        throw GoogleCloudGax.RequestError.binding("'request.secret.name' is not set or is empty")
      }
      return "/v1/\(pathVariable0)"
    }()
    var query = [URLQueryItem(name: "$alt", value: "json;enum-encoding=int")]
    let encoder = GoogleCloudGax.QueryParameterEncoder()
    query.append(contentsOf: try encoder.encode(request.updateMask, prefix: "updateMask"))
    var req = try await self.inner.Request(path: path, query: query)
    req.httpMethod = "PATCH"
    if let body = request.secret {
      req.setValue("application/json", forHTTPHeaderField: "Content-Type")
      req.httpBody = try JSONEncoder().encode(body)
    }
    let (data, response) = try await self.inner.data(for: req)
    if !(200..<300).contains(response.statusCode) {
      throw RequestError.http(
        HTTPDetails(
          http_status_code: response.statusCode,
          headers: [:],
          payload: data,
        ))
    }
    return try ProtoJSONDecoder().decode(Secret.self, from: data)
  }

  /// Deletes a [Secret][google.cloud.secretmanager.v1.Secret].
  ///
  /// @Snippet(path: "SecretManagerService_DeleteSecret")
  public func deleteSecret(request: DeleteSecretRequest) async throws {
    let path = try { () throws -> String in
      guard let pathVariable0 = request.name as String?, !pathVariable0.isEmpty else {
        throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
      }
      return "/v1/\(pathVariable0)"
    }()
    var query = [URLQueryItem(name: "$alt", value: "json;enum-encoding=int")]
    let encoder = GoogleCloudGax.QueryParameterEncoder()
    query.append(contentsOf: try encoder.encode(request.etag, prefix: "etag"))
    var req = try await self.inner.Request(path: path, query: query)
    req.httpMethod = "DELETE"
    let (data, response) = try await self.inner.data(for: req)
    if !(200..<300).contains(response.statusCode) {
      throw RequestError.http(
        HTTPDetails(
          http_status_code: response.statusCode,
          headers: [:],
          payload: data,
        ))
    }
  }

  /// Lists [SecretVersions][google.cloud.secretmanager.v1.SecretVersion]. This
  /// call does not return secret data.
  ///
  /// @Snippet(path: "SecretManagerService_ListSecretVersions")
  public func listSecretVersions(request: ListSecretVersionsRequest) async throws
    -> ListSecretVersionsResponse
  {
    let path = try { () throws -> String in
      guard let pathVariable0 = request.parent as String?, !pathVariable0.isEmpty else {
        throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
      }
      return "/v1/\(pathVariable0)/versions"
    }()
    var query = [URLQueryItem(name: "$alt", value: "json;enum-encoding=int")]
    let encoder = GoogleCloudGax.QueryParameterEncoder()
    query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
    query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
    query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
    var req = try await self.inner.Request(path: path, query: query)
    req.httpMethod = "GET"
    let (data, response) = try await self.inner.data(for: req)
    if !(200..<300).contains(response.statusCode) {
      throw RequestError.http(
        HTTPDetails(
          http_status_code: response.statusCode,
          headers: [:],
          payload: data,
        ))
    }
    return try ProtoJSONDecoder().decode(ListSecretVersionsResponse.self, from: data)
  }

  /// Gets metadata for a
  /// [SecretVersion][google.cloud.secretmanager.v1.SecretVersion].
  ///
  /// `projects/*/secrets/*/versions/latest` is an alias to the most recently
  /// created [SecretVersion][google.cloud.secretmanager.v1.SecretVersion].
  ///
  /// @Snippet(path: "SecretManagerService_GetSecretVersion")
  public func getSecretVersion(request: GetSecretVersionRequest) async throws
    -> SecretVersion
  {
    let path = try { () throws -> String in
      guard let pathVariable0 = request.name as String?, !pathVariable0.isEmpty else {
        throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
      }
      return "/v1/\(pathVariable0)"
    }()
    let query = [URLQueryItem(name: "$alt", value: "json;enum-encoding=int")]
    var req = try await self.inner.Request(path: path, query: query)
    req.httpMethod = "GET"
    let (data, response) = try await self.inner.data(for: req)
    if !(200..<300).contains(response.statusCode) {
      throw RequestError.http(
        HTTPDetails(
          http_status_code: response.statusCode,
          headers: [:],
          payload: data,
        ))
    }
    return try ProtoJSONDecoder().decode(SecretVersion.self, from: data)
  }

  /// Accesses a [SecretVersion][google.cloud.secretmanager.v1.SecretVersion].
  /// This call returns the secret data.
  ///
  /// `projects/*/secrets/*/versions/latest` is an alias to the most recently
  /// created [SecretVersion][google.cloud.secretmanager.v1.SecretVersion].
  ///
  /// @Snippet(path: "SecretManagerService_AccessSecretVersion")
  public func accessSecretVersion(request: AccessSecretVersionRequest) async throws
    -> AccessSecretVersionResponse
  {
    let path = try { () throws -> String in
      guard let pathVariable0 = request.name as String?, !pathVariable0.isEmpty else {
        throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
      }
      return "/v1/\(pathVariable0):access"
    }()
    let query = [URLQueryItem(name: "$alt", value: "json;enum-encoding=int")]
    var req = try await self.inner.Request(path: path, query: query)
    req.httpMethod = "GET"
    let (data, response) = try await self.inner.data(for: req)
    if !(200..<300).contains(response.statusCode) {
      throw RequestError.http(
        HTTPDetails(
          http_status_code: response.statusCode,
          headers: [:],
          payload: data,
        ))
    }
    return try ProtoJSONDecoder().decode(AccessSecretVersionResponse.self, from: data)
  }

  /// Disables a [SecretVersion][google.cloud.secretmanager.v1.SecretVersion].
  ///
  /// Sets the [state][google.cloud.secretmanager.v1.SecretVersion.state] of the
  /// [SecretVersion][google.cloud.secretmanager.v1.SecretVersion] to
  /// [DISABLED][google.cloud.secretmanager.v1.SecretVersion.State.DISABLED].
  ///
  /// @Snippet(path: "SecretManagerService_DisableSecretVersion")
  public func disableSecretVersion(request: DisableSecretVersionRequest) async throws
    -> SecretVersion
  {
    let path = try { () throws -> String in
      guard let pathVariable0 = request.name as String?, !pathVariable0.isEmpty else {
        throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
      }
      return "/v1/\(pathVariable0):disable"
    }()
    let query = [URLQueryItem(name: "$alt", value: "json;enum-encoding=int")]
    var req = try await self.inner.Request(path: path, query: query)
    req.httpMethod = "POST"
    req.setValue("application/json", forHTTPHeaderField: "Content-Type")
    req.httpBody = try JSONEncoder().encode(request)
    let (data, response) = try await self.inner.data(for: req)
    if !(200..<300).contains(response.statusCode) {
      throw RequestError.http(
        HTTPDetails(
          http_status_code: response.statusCode,
          headers: [:],
          payload: data,
        ))
    }
    return try ProtoJSONDecoder().decode(SecretVersion.self, from: data)
  }

  /// Enables a [SecretVersion][google.cloud.secretmanager.v1.SecretVersion].
  ///
  /// Sets the [state][google.cloud.secretmanager.v1.SecretVersion.state] of the
  /// [SecretVersion][google.cloud.secretmanager.v1.SecretVersion] to
  /// [ENABLED][google.cloud.secretmanager.v1.SecretVersion.State.ENABLED].
  ///
  /// @Snippet(path: "SecretManagerService_EnableSecretVersion")
  public func enableSecretVersion(request: EnableSecretVersionRequest) async throws
    -> SecretVersion
  {
    let path = try { () throws -> String in
      guard let pathVariable0 = request.name as String?, !pathVariable0.isEmpty else {
        throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
      }
      return "/v1/\(pathVariable0):enable"
    }()
    let query = [URLQueryItem(name: "$alt", value: "json;enum-encoding=int")]
    var req = try await self.inner.Request(path: path, query: query)
    req.httpMethod = "POST"
    req.setValue("application/json", forHTTPHeaderField: "Content-Type")
    req.httpBody = try JSONEncoder().encode(request)
    let (data, response) = try await self.inner.data(for: req)
    if !(200..<300).contains(response.statusCode) {
      throw RequestError.http(
        HTTPDetails(
          http_status_code: response.statusCode,
          headers: [:],
          payload: data,
        ))
    }
    return try ProtoJSONDecoder().decode(SecretVersion.self, from: data)
  }

  /// Destroys a [SecretVersion][google.cloud.secretmanager.v1.SecretVersion].
  ///
  /// Sets the [state][google.cloud.secretmanager.v1.SecretVersion.state] of the
  /// [SecretVersion][google.cloud.secretmanager.v1.SecretVersion] to
  /// [DESTROYED][google.cloud.secretmanager.v1.SecretVersion.State.DESTROYED]
  /// and irrevocably destroys the secret data.
  ///
  /// @Snippet(path: "SecretManagerService_DestroySecretVersion")
  public func destroySecretVersion(request: DestroySecretVersionRequest) async throws
    -> SecretVersion
  {
    let path = try { () throws -> String in
      guard let pathVariable0 = request.name as String?, !pathVariable0.isEmpty else {
        throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
      }
      return "/v1/\(pathVariable0):destroy"
    }()
    let query = [URLQueryItem(name: "$alt", value: "json;enum-encoding=int")]
    var req = try await self.inner.Request(path: path, query: query)
    req.httpMethod = "POST"
    req.setValue("application/json", forHTTPHeaderField: "Content-Type")
    req.httpBody = try JSONEncoder().encode(request)
    let (data, response) = try await self.inner.data(for: req)
    if !(200..<300).contains(response.statusCode) {
      throw RequestError.http(
        HTTPDetails(
          http_status_code: response.statusCode,
          headers: [:],
          payload: data,
        ))
    }
    return try ProtoJSONDecoder().decode(SecretVersion.self, from: data)
  }

  /// Sets the access control policy on the specified secret. Replaces any
  /// existing policy.
  ///
  /// Permissions on
  /// [SecretVersions][google.cloud.secretmanager.v1.SecretVersion] are enforced
  /// according to the policy set on the associated
  /// [Secret][google.cloud.secretmanager.v1.Secret].
  ///
  /// @Snippet(path: "SecretManagerService_SetIamPolicy")
  public func setIamPolicy(request: SetIamPolicyRequest) async throws
    -> Policy
  {
    let path = try { () throws -> String in
      guard let pathVariable0 = request.resource as String?, !pathVariable0.isEmpty else {
        throw GoogleCloudGax.RequestError.binding("'request.resource' is not set or is empty")
      }
      return "/v1/\(pathVariable0):setIamPolicy"
    }()
    let query = [URLQueryItem(name: "$alt", value: "json;enum-encoding=int")]
    var req = try await self.inner.Request(path: path, query: query)
    req.httpMethod = "POST"
    req.setValue("application/json", forHTTPHeaderField: "Content-Type")
    req.httpBody = try JSONEncoder().encode(request)
    let (data, response) = try await self.inner.data(for: req)
    if !(200..<300).contains(response.statusCode) {
      throw RequestError.http(
        HTTPDetails(
          http_status_code: response.statusCode,
          headers: [:],
          payload: data,
        ))
    }
    return try ProtoJSONDecoder().decode(Policy.self, from: data)
  }

  /// Gets the access control policy for a secret.
  /// Returns empty policy if the secret exists and does not have a policy set.
  ///
  /// @Snippet(path: "SecretManagerService_GetIamPolicy")
  public func getIamPolicy(request: GetIamPolicyRequest) async throws
    -> Policy
  {
    let path = try { () throws -> String in
      guard let pathVariable0 = request.resource as String?, !pathVariable0.isEmpty else {
        throw GoogleCloudGax.RequestError.binding("'request.resource' is not set or is empty")
      }
      return "/v1/\(pathVariable0):getIamPolicy"
    }()
    var query = [URLQueryItem(name: "$alt", value: "json;enum-encoding=int")]
    let encoder = GoogleCloudGax.QueryParameterEncoder()
    query.append(contentsOf: try encoder.encode(request.options, prefix: "options"))
    var req = try await self.inner.Request(path: path, query: query)
    req.httpMethod = "GET"
    let (data, response) = try await self.inner.data(for: req)
    if !(200..<300).contains(response.statusCode) {
      throw RequestError.http(
        HTTPDetails(
          http_status_code: response.statusCode,
          headers: [:],
          payload: data,
        ))
    }
    return try ProtoJSONDecoder().decode(Policy.self, from: data)
  }

  /// Returns permissions that a caller has for the specified secret.
  /// If the secret does not exist, this call returns an empty set of
  /// permissions, not a NOT_FOUND error.
  ///
  /// Note: This operation is designed to be used for building permission-aware
  /// UIs and command-line tools, not for authorization checking. This operation
  /// may "fail open" without warning.
  ///
  /// @Snippet(path: "SecretManagerService_TestIamPermissions")
  public func testIamPermissions(request: TestIamPermissionsRequest) async throws
    -> TestIamPermissionsResponse
  {
    let path = try { () throws -> String in
      guard let pathVariable0 = request.resource as String?, !pathVariable0.isEmpty else {
        throw GoogleCloudGax.RequestError.binding("'request.resource' is not set or is empty")
      }
      return "/v1/\(pathVariable0):testIamPermissions"
    }()
    let query = [URLQueryItem(name: "$alt", value: "json;enum-encoding=int")]
    var req = try await self.inner.Request(path: path, query: query)
    req.httpMethod = "POST"
    req.setValue("application/json", forHTTPHeaderField: "Content-Type")
    req.httpBody = try JSONEncoder().encode(request)
    let (data, response) = try await self.inner.data(for: req)
    if !(200..<300).contains(response.statusCode) {
      throw RequestError.http(
        HTTPDetails(
          http_status_code: response.statusCode,
          headers: [:],
          payload: data,
        ))
    }
    return try ProtoJSONDecoder().decode(TestIamPermissionsResponse.self, from: data)
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "SecretManagerService_ListLocations")
  public func listLocations(request: ListLocationsRequest) async throws
    -> ListLocationsResponse
  {
    let path = try { () throws -> String in
      guard let pathVariable0 = request.name as String?, !pathVariable0.isEmpty else {
        throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
      }
      return "/v1/\(pathVariable0)/locations"
    }()
    var query = [URLQueryItem(name: "$alt", value: "json;enum-encoding=int")]
    let encoder = GoogleCloudGax.QueryParameterEncoder()
    query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
    query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
    query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
    var req = try await self.inner.Request(path: path, query: query)
    req.httpMethod = "GET"
    let (data, response) = try await self.inner.data(for: req)
    if !(200..<300).contains(response.statusCode) {
      throw RequestError.http(
        HTTPDetails(
          http_status_code: response.statusCode,
          headers: [:],
          payload: data,
        ))
    }
    return try ProtoJSONDecoder().decode(ListLocationsResponse.self, from: data)
  }

  /// Gets information about a location.
  ///
  /// @Snippet(path: "SecretManagerService_GetLocation")
  public func getLocation(request: GetLocationRequest) async throws
    -> Location
  {
    let path = try { () throws -> String in
      guard let pathVariable0 = request.name as String?, !pathVariable0.isEmpty else {
        throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
      }
      return "/v1/\(pathVariable0)"
    }()
    let query = [URLQueryItem(name: "$alt", value: "json;enum-encoding=int")]
    var req = try await self.inner.Request(path: path, query: query)
    req.httpMethod = "GET"
    let (data, response) = try await self.inner.data(for: req)
    if !(200..<300).contains(response.statusCode) {
      throw RequestError.http(
        HTTPDetails(
          http_status_code: response.statusCode,
          headers: [:],
          payload: data,
        ))
    }
    return try ProtoJSONDecoder().decode(Location.self, from: data)
  }
}
