// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleIAMV1
import GoogleWKT
@_spi(GoogleCloudInternal) import GoogleGax

extension Clients {
  final class SecretManagerServiceRetry: SecretManagerServiceStub {
    let inner: any SecretManagerServiceStub
    let options: GoogleGax.ClientOptions

    public init(_ inner: any SecretManagerServiceStub, options: GoogleGax.ClientOptions) {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func listSecrets(
      request: ListSecretsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecretManagerV1.ListSecretsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListSecretsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudSecretManagerV1.ListSecretsResponse
          in
          return try await self.inner.listSecrets(request: r, options: o)
        })
    }

    public func createSecret(
      request: CreateSecretRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecretManagerV1.Secret {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateSecretRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudSecretManagerV1.Secret
          in
          return try await self.inner.createSecret(request: r, options: o)
        })
    }

    public func addSecretVersion(
      request: AddSecretVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecretManagerV1.SecretVersion {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: AddSecretVersionRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudSecretManagerV1.SecretVersion
          in
          return try await self.inner.addSecretVersion(request: r, options: o)
        })
    }

    public func getSecret(
      request: GetSecretRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecretManagerV1.Secret {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetSecretRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudSecretManagerV1.Secret
          in
          return try await self.inner.getSecret(request: r, options: o)
        })
    }

    public func updateSecret(
      request: UpdateSecretRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecretManagerV1.Secret {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateSecretRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudSecretManagerV1.Secret
          in
          return try await self.inner.updateSecret(request: r, options: o)
        })
    }

    public func deleteSecret(
      request: DeleteSecretRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: { (r: DeleteSecretRequest, o: GoogleGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteSecret(request: r, options: o)
        })
    }

    public func listSecretVersions(
      request: ListSecretVersionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecretManagerV1.ListSecretVersionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListSecretVersionsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudSecretManagerV1.ListSecretVersionsResponse
          in
          return try await self.inner.listSecretVersions(request: r, options: o)
        })
    }

    public func getSecretVersion(
      request: GetSecretVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecretManagerV1.SecretVersion {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetSecretVersionRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudSecretManagerV1.SecretVersion
          in
          return try await self.inner.getSecretVersion(request: r, options: o)
        })
    }

    public func accessSecretVersion(
      request: AccessSecretVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecretManagerV1.AccessSecretVersionResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: AccessSecretVersionRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudSecretManagerV1.AccessSecretVersionResponse
          in
          return try await self.inner.accessSecretVersion(request: r, options: o)
        })
    }

    public func disableSecretVersion(
      request: DisableSecretVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecretManagerV1.SecretVersion {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DisableSecretVersionRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudSecretManagerV1.SecretVersion
          in
          return try await self.inner.disableSecretVersion(request: r, options: o)
        })
    }

    public func enableSecretVersion(
      request: EnableSecretVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecretManagerV1.SecretVersion {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: EnableSecretVersionRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudSecretManagerV1.SecretVersion
          in
          return try await self.inner.enableSecretVersion(request: r, options: o)
        })
    }

    public func destroySecretVersion(
      request: DestroySecretVersionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecretManagerV1.SecretVersion {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DestroySecretVersionRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudSecretManagerV1.SecretVersion
          in
          return try await self.inner.destroySecretVersion(request: r, options: o)
        })
    }

    public func setIamPolicy(
      request: GoogleIAMV1.SetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleIAMV1.SetIamPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV1.Policy
          in
          return try await self.inner.setIamPolicy(request: r, options: o)
        })
    }

    public func getIamPolicy(
      request: GoogleIAMV1.GetIamPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.Policy {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleIAMV1.GetIamPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV1.Policy
          in
          return try await self.inner.getIamPolicy(request: r, options: o)
        })
    }

    public func testIamPermissions(
      request: GoogleIAMV1.TestIamPermissionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV1.TestIamPermissionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: GoogleIAMV1.TestIamPermissionsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV1.TestIamPermissionsResponse
          in
          return try await self.inner.testIamPermissions(request: r, options: o)
        })
    }

    public func enableManagedRotation(
      request: EnableManagedRotationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecretManagerV1.SecretVersion {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: EnableManagedRotationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudSecretManagerV1.SecretVersion
          in
          return try await self.inner.enableManagedRotation(request: r, options: o)
        })
    }

    public func rotateSecret(
      request: RotateSecretRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudSecretManagerV1.SecretVersion {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: RotateSecretRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudSecretManagerV1.SecretVersion
          in
          return try await self.inner.rotateSecret(request: r, options: o)
        })
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLocation.ListLocationsResponse
          in
          return try await self.inner.listLocations(request: r, options: o)
        })
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleCloudLocation.GetLocationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLocation.Location
          in
          return try await self.inner.getLocation(request: r, options: o)
        })
    }
  }
}
