// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif

import GoogleCloudAuth
import GoogleCloudGax
import GoogleCloudLocation
import GoogleCloudWkt
import GoogleIamV1
import Logging

extension Clients {
  final class SecretManagerServiceLogging: SecretManagerServiceStub {
    let inner: any SecretManagerServiceStub
    let logger: Logging.Logger

    public init(_ inner: any SecretManagerServiceStub, logger: Logging.Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "GoogleCloudSecretmanagerV1"
      logger[metadataKey: "gcp.client.service"] = "secretmanager"
      logger[metadataKey: "gcp.experimental.swift.client"] = "SecretManagerService"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      name: String,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func listSecrets(
      request: ListSecretsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> ListSecretsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listSecrets",
        action: {
          (r: ListSecretsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> ListSecretsResponse
          in
          return try await self.inner.listSecrets(request: r, options: o)
        })
    }

    public func createSecret(
      request: CreateSecretRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> Secret {
      try await self._intercept(
        request: request,
        options: options,
        name: "createSecret",
        action: {
          (r: CreateSecretRequest, o: GoogleCloudGax.RequestOptions) async throws -> Secret
          in
          return try await self.inner.createSecret(request: r, options: o)
        })
    }

    public func addSecretVersion(
      request: AddSecretVersionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> SecretVersion {
      try await self._intercept(
        request: request,
        options: options,
        name: "addSecretVersion",
        action: {
          (r: AddSecretVersionRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> SecretVersion
          in
          return try await self.inner.addSecretVersion(request: r, options: o)
        })
    }

    public func getSecret(
      request: GetSecretRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> Secret {
      try await self._intercept(
        request: request,
        options: options,
        name: "getSecret",
        action: {
          (r: GetSecretRequest, o: GoogleCloudGax.RequestOptions) async throws -> Secret
          in
          return try await self.inner.getSecret(request: r, options: o)
        })
    }

    public func updateSecret(
      request: UpdateSecretRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> Secret {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateSecret",
        action: {
          (r: UpdateSecretRequest, o: GoogleCloudGax.RequestOptions) async throws -> Secret
          in
          return try await self.inner.updateSecret(request: r, options: o)
        })
    }

    public func deleteSecret(
      request: DeleteSecretRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteSecret",
        action: { (r: DeleteSecretRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
          return try await self.inner.deleteSecret(request: r, options: o)
        })
    }

    public func listSecretVersions(
      request: ListSecretVersionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> ListSecretVersionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listSecretVersions",
        action: {
          (r: ListSecretVersionsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> ListSecretVersionsResponse
          in
          return try await self.inner.listSecretVersions(request: r, options: o)
        })
    }

    public func getSecretVersion(
      request: GetSecretVersionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> SecretVersion {
      try await self._intercept(
        request: request,
        options: options,
        name: "getSecretVersion",
        action: {
          (r: GetSecretVersionRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> SecretVersion
          in
          return try await self.inner.getSecretVersion(request: r, options: o)
        })
    }

    public func accessSecretVersion(
      request: AccessSecretVersionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> AccessSecretVersionResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "accessSecretVersion",
        action: {
          (r: AccessSecretVersionRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> AccessSecretVersionResponse
          in
          return try await self.inner.accessSecretVersion(request: r, options: o)
        })
    }

    public func disableSecretVersion(
      request: DisableSecretVersionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> SecretVersion {
      try await self._intercept(
        request: request,
        options: options,
        name: "disableSecretVersion",
        action: {
          (r: DisableSecretVersionRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> SecretVersion
          in
          return try await self.inner.disableSecretVersion(request: r, options: o)
        })
    }

    public func enableSecretVersion(
      request: EnableSecretVersionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> SecretVersion {
      try await self._intercept(
        request: request,
        options: options,
        name: "enableSecretVersion",
        action: {
          (r: EnableSecretVersionRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> SecretVersion
          in
          return try await self.inner.enableSecretVersion(request: r, options: o)
        })
    }

    public func destroySecretVersion(
      request: DestroySecretVersionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> SecretVersion {
      try await self._intercept(
        request: request,
        options: options,
        name: "destroySecretVersion",
        action: {
          (r: DestroySecretVersionRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> SecretVersion
          in
          return try await self.inner.destroySecretVersion(request: r, options: o)
        })
    }

    public func setIamPolicy(
      request: SetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> Policy {
      try await self._intercept(
        request: request,
        options: options,
        name: "setIamPolicy",
        action: {
          (r: SetIamPolicyRequest, o: GoogleCloudGax.RequestOptions) async throws -> Policy
          in
          return try await self.inner.setIamPolicy(request: r, options: o)
        })
    }

    public func getIamPolicy(
      request: GetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> Policy {
      try await self._intercept(
        request: request,
        options: options,
        name: "getIamPolicy",
        action: {
          (r: GetIamPolicyRequest, o: GoogleCloudGax.RequestOptions) async throws -> Policy
          in
          return try await self.inner.getIamPolicy(request: r, options: o)
        })
    }

    public func testIamPermissions(
      request: TestIamPermissionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> TestIamPermissionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "testIamPermissions",
        action: {
          (r: TestIamPermissionsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> TestIamPermissionsResponse
          in
          return try await self.inner.testIamPermissions(request: r, options: o)
        })
    }

    public func listLocations(
      request: ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> ListLocationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listLocations",
        action: {
          (r: ListLocationsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> ListLocationsResponse
          in
          return try await self.inner.listLocations(request: r, options: o)
        })
    }

    public func getLocation(
      request: GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> Location {
      try await self._intercept(
        request: request,
        options: options,
        name: "getLocation",
        action: {
          (r: GetLocationRequest, o: GoogleCloudGax.RequestOptions) async throws -> Location
          in
          return try await self.inner.getLocation(request: r, options: o)
        })
    }
  }
}
