// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif

import GoogleCloudAuth
import GoogleCloudGax
import GoogleCloudLocation
import GoogleCloudWkt
import GoogleIamV1
import Logging

/// Secret Manager Service
///
/// Manages secrets and operations using those secrets. Implements a REST
/// model with the following objects:
///
/// * [Secret][google.cloud.secretmanager.v1.Secret]
/// * [SecretVersion][google.cloud.secretmanager.v1.SecretVersion]
///
/// [google.cloud.secretmanager.v1.Secret]: <doc:Secret>
/// [google.cloud.secretmanager.v1.SecretVersion]: <doc:SecretVersion>
///
/// @Snippet(path: "SecretManagerServiceQuickstart")
public protocol SecretManagerService {
  /// Lists [Secrets][google.cloud.secretmanager.v1.Secret].
  ///
  /// [google.cloud.secretmanager.v1.Secret]: <doc:Secret>
  ///
  /// @Snippet(path: "SecretManagerService_ListSecrets")
  func listSecrets(request: ListSecretsRequest) async throws -> ListSecretsResponse

  /// Lists [Secrets][google.cloud.secretmanager.v1.Secret].
  ///
  /// [google.cloud.secretmanager.v1.Secret]: <doc:Secret>
  func listSecrets(byItem: ListSecretsRequest) throws -> any AsyncSequence<Secret, Error>

  /// Creates a new [Secret][google.cloud.secretmanager.v1.Secret] containing no
  /// [SecretVersions][google.cloud.secretmanager.v1.SecretVersion].
  ///
  /// [google.cloud.secretmanager.v1.Secret]: <doc:Secret>
  /// [google.cloud.secretmanager.v1.SecretVersion]: <doc:SecretVersion>
  ///
  /// @Snippet(path: "SecretManagerService_CreateSecret")
  func createSecret(request: CreateSecretRequest) async throws -> Secret

  /// Creates a new [SecretVersion][google.cloud.secretmanager.v1.SecretVersion]
  /// containing secret data and attaches it to an existing
  /// [Secret][google.cloud.secretmanager.v1.Secret].
  ///
  /// [google.cloud.secretmanager.v1.Secret]: <doc:Secret>
  /// [google.cloud.secretmanager.v1.SecretVersion]: <doc:SecretVersion>
  ///
  /// @Snippet(path: "SecretManagerService_AddSecretVersion")
  func addSecretVersion(request: AddSecretVersionRequest) async throws -> SecretVersion

  /// Gets metadata for a given [Secret][google.cloud.secretmanager.v1.Secret].
  ///
  /// [google.cloud.secretmanager.v1.Secret]: <doc:Secret>
  ///
  /// @Snippet(path: "SecretManagerService_GetSecret")
  func getSecret(request: GetSecretRequest) async throws -> Secret

  /// Updates metadata of an existing
  /// [Secret][google.cloud.secretmanager.v1.Secret].
  ///
  /// [google.cloud.secretmanager.v1.Secret]: <doc:Secret>
  ///
  /// @Snippet(path: "SecretManagerService_UpdateSecret")
  func updateSecret(request: UpdateSecretRequest) async throws -> Secret

  /// Deletes a [Secret][google.cloud.secretmanager.v1.Secret].
  ///
  /// [google.cloud.secretmanager.v1.Secret]: <doc:Secret>
  ///
  /// @Snippet(path: "SecretManagerService_DeleteSecret")
  func deleteSecret(request: DeleteSecretRequest) async throws

  /// Lists [SecretVersions][google.cloud.secretmanager.v1.SecretVersion]. This
  /// call does not return secret data.
  ///
  /// [google.cloud.secretmanager.v1.SecretVersion]: <doc:SecretVersion>
  ///
  /// @Snippet(path: "SecretManagerService_ListSecretVersions")
  func listSecretVersions(request: ListSecretVersionsRequest) async throws
    -> ListSecretVersionsResponse

  /// Lists [SecretVersions][google.cloud.secretmanager.v1.SecretVersion]. This
  /// call does not return secret data.
  ///
  /// [google.cloud.secretmanager.v1.SecretVersion]: <doc:SecretVersion>
  func listSecretVersions(byItem: ListSecretVersionsRequest) throws -> any AsyncSequence<
    SecretVersion, Error
  >

  /// Gets metadata for a
  /// [SecretVersion][google.cloud.secretmanager.v1.SecretVersion].
  ///
  /// `projects/*/secrets/*/versions/latest` is an alias to the most recently
  /// created [SecretVersion][google.cloud.secretmanager.v1.SecretVersion].
  ///
  /// [google.cloud.secretmanager.v1.SecretVersion]: <doc:SecretVersion>
  ///
  /// @Snippet(path: "SecretManagerService_GetSecretVersion")
  func getSecretVersion(request: GetSecretVersionRequest) async throws -> SecretVersion

  /// Accesses a [SecretVersion][google.cloud.secretmanager.v1.SecretVersion].
  /// This call returns the secret data.
  ///
  /// `projects/*/secrets/*/versions/latest` is an alias to the most recently
  /// created [SecretVersion][google.cloud.secretmanager.v1.SecretVersion].
  ///
  /// [google.cloud.secretmanager.v1.SecretVersion]: <doc:SecretVersion>
  ///
  /// @Snippet(path: "SecretManagerService_AccessSecretVersion")
  func accessSecretVersion(request: AccessSecretVersionRequest) async throws
    -> AccessSecretVersionResponse

  /// Disables a [SecretVersion][google.cloud.secretmanager.v1.SecretVersion].
  ///
  /// Sets the [state][google.cloud.secretmanager.v1.SecretVersion.state] of the
  /// [SecretVersion][google.cloud.secretmanager.v1.SecretVersion] to
  /// [DISABLED][google.cloud.secretmanager.v1.SecretVersion.State.DISABLED].
  ///
  /// [google.cloud.secretmanager.v1.SecretVersion]: <doc:SecretVersion>
  /// [google.cloud.secretmanager.v1.SecretVersion.State.DISABLED]: <doc:SecretVersion/State/disabled>
  /// [google.cloud.secretmanager.v1.SecretVersion.state]: <doc:SecretVersion/state>
  ///
  /// @Snippet(path: "SecretManagerService_DisableSecretVersion")
  func disableSecretVersion(request: DisableSecretVersionRequest) async throws -> SecretVersion

  /// Enables a [SecretVersion][google.cloud.secretmanager.v1.SecretVersion].
  ///
  /// Sets the [state][google.cloud.secretmanager.v1.SecretVersion.state] of the
  /// [SecretVersion][google.cloud.secretmanager.v1.SecretVersion] to
  /// [ENABLED][google.cloud.secretmanager.v1.SecretVersion.State.ENABLED].
  ///
  /// [google.cloud.secretmanager.v1.SecretVersion]: <doc:SecretVersion>
  /// [google.cloud.secretmanager.v1.SecretVersion.State.ENABLED]: <doc:SecretVersion/State/enabled>
  /// [google.cloud.secretmanager.v1.SecretVersion.state]: <doc:SecretVersion/state>
  ///
  /// @Snippet(path: "SecretManagerService_EnableSecretVersion")
  func enableSecretVersion(request: EnableSecretVersionRequest) async throws -> SecretVersion

  /// Destroys a [SecretVersion][google.cloud.secretmanager.v1.SecretVersion].
  ///
  /// Sets the [state][google.cloud.secretmanager.v1.SecretVersion.state] of the
  /// [SecretVersion][google.cloud.secretmanager.v1.SecretVersion] to
  /// [DESTROYED][google.cloud.secretmanager.v1.SecretVersion.State.DESTROYED]
  /// and irrevocably destroys the secret data.
  ///
  /// [google.cloud.secretmanager.v1.SecretVersion]: <doc:SecretVersion>
  /// [google.cloud.secretmanager.v1.SecretVersion.State.DESTROYED]: <doc:SecretVersion/State/destroyed>
  /// [google.cloud.secretmanager.v1.SecretVersion.state]: <doc:SecretVersion/state>
  ///
  /// @Snippet(path: "SecretManagerService_DestroySecretVersion")
  func destroySecretVersion(request: DestroySecretVersionRequest) async throws -> SecretVersion

  /// Sets the access control policy on the specified secret. Replaces any
  /// existing policy.
  ///
  /// Permissions on
  /// [SecretVersions][google.cloud.secretmanager.v1.SecretVersion] are enforced
  /// according to the policy set on the associated
  /// [Secret][google.cloud.secretmanager.v1.Secret].
  ///
  /// [google.cloud.secretmanager.v1.Secret]: <doc:Secret>
  /// [google.cloud.secretmanager.v1.SecretVersion]: <doc:SecretVersion>
  ///
  /// @Snippet(path: "SecretManagerService_SetIamPolicy")
  func setIamPolicy(request: SetIamPolicyRequest) async throws -> Policy

  /// Gets the access control policy for a secret.
  /// Returns empty policy if the secret exists and does not have a policy set.
  ///
  /// @Snippet(path: "SecretManagerService_GetIamPolicy")
  func getIamPolicy(request: GetIamPolicyRequest) async throws -> Policy

  /// Returns permissions that a caller has for the specified secret.
  /// If the secret does not exist, this call returns an empty set of
  /// permissions, not a NOT_FOUND error.
  ///
  /// Note: This operation is designed to be used for building permission-aware
  /// UIs and command-line tools, not for authorization checking. This operation
  /// may "fail open" without warning.
  ///
  /// @Snippet(path: "SecretManagerService_TestIamPermissions")
  func testIamPermissions(request: TestIamPermissionsRequest) async throws
    -> TestIamPermissionsResponse

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "SecretManagerService_ListLocations")
  func listLocations(request: ListLocationsRequest) async throws -> ListLocationsResponse

  /// Lists information about the supported locations for this service.
  func listLocations(byItem: ListLocationsRequest) throws -> any AsyncSequence<
    GoogleCloudLocation.Location, Error
  >

  /// Gets information about a location.
  ///
  /// @Snippet(path: "SecretManagerService_GetLocation")
  func getLocation(request: GetLocationRequest) async throws -> Location

  /// Lists [Secrets][google.cloud.secretmanager.v1.Secret].
  ///
  /// [google.cloud.secretmanager.v1.Secret]: <doc:Secret>
  ///
  /// @Snippet(path: "SecretManagerService_ListSecrets")
  func listSecrets(
    request: ListSecretsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> ListSecretsResponse

  /// Lists [Secrets][google.cloud.secretmanager.v1.Secret].
  ///
  /// [google.cloud.secretmanager.v1.Secret]: <doc:Secret>
  func listSecrets(
    byItem: ListSecretsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Secret, Error>

  /// Creates a new [Secret][google.cloud.secretmanager.v1.Secret] containing no
  /// [SecretVersions][google.cloud.secretmanager.v1.SecretVersion].
  ///
  /// [google.cloud.secretmanager.v1.Secret]: <doc:Secret>
  /// [google.cloud.secretmanager.v1.SecretVersion]: <doc:SecretVersion>
  ///
  /// @Snippet(path: "SecretManagerService_CreateSecret")
  func createSecret(
    request: CreateSecretRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> Secret

  /// Creates a new [SecretVersion][google.cloud.secretmanager.v1.SecretVersion]
  /// containing secret data and attaches it to an existing
  /// [Secret][google.cloud.secretmanager.v1.Secret].
  ///
  /// [google.cloud.secretmanager.v1.Secret]: <doc:Secret>
  /// [google.cloud.secretmanager.v1.SecretVersion]: <doc:SecretVersion>
  ///
  /// @Snippet(path: "SecretManagerService_AddSecretVersion")
  func addSecretVersion(
    request: AddSecretVersionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> SecretVersion

  /// Gets metadata for a given [Secret][google.cloud.secretmanager.v1.Secret].
  ///
  /// [google.cloud.secretmanager.v1.Secret]: <doc:Secret>
  ///
  /// @Snippet(path: "SecretManagerService_GetSecret")
  func getSecret(
    request: GetSecretRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> Secret

  /// Updates metadata of an existing
  /// [Secret][google.cloud.secretmanager.v1.Secret].
  ///
  /// [google.cloud.secretmanager.v1.Secret]: <doc:Secret>
  ///
  /// @Snippet(path: "SecretManagerService_UpdateSecret")
  func updateSecret(
    request: UpdateSecretRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> Secret

  /// Deletes a [Secret][google.cloud.secretmanager.v1.Secret].
  ///
  /// [google.cloud.secretmanager.v1.Secret]: <doc:Secret>
  ///
  /// @Snippet(path: "SecretManagerService_DeleteSecret")
  func deleteSecret(
    request: DeleteSecretRequest, options: GoogleCloudGax.RequestOptions
  ) async throws

  /// Lists [SecretVersions][google.cloud.secretmanager.v1.SecretVersion]. This
  /// call does not return secret data.
  ///
  /// [google.cloud.secretmanager.v1.SecretVersion]: <doc:SecretVersion>
  ///
  /// @Snippet(path: "SecretManagerService_ListSecretVersions")
  func listSecretVersions(
    request: ListSecretVersionsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> ListSecretVersionsResponse

  /// Lists [SecretVersions][google.cloud.secretmanager.v1.SecretVersion]. This
  /// call does not return secret data.
  ///
  /// [google.cloud.secretmanager.v1.SecretVersion]: <doc:SecretVersion>
  func listSecretVersions(
    byItem: ListSecretVersionsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<SecretVersion, Error>

  /// Gets metadata for a
  /// [SecretVersion][google.cloud.secretmanager.v1.SecretVersion].
  ///
  /// `projects/*/secrets/*/versions/latest` is an alias to the most recently
  /// created [SecretVersion][google.cloud.secretmanager.v1.SecretVersion].
  ///
  /// [google.cloud.secretmanager.v1.SecretVersion]: <doc:SecretVersion>
  ///
  /// @Snippet(path: "SecretManagerService_GetSecretVersion")
  func getSecretVersion(
    request: GetSecretVersionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> SecretVersion

  /// Accesses a [SecretVersion][google.cloud.secretmanager.v1.SecretVersion].
  /// This call returns the secret data.
  ///
  /// `projects/*/secrets/*/versions/latest` is an alias to the most recently
  /// created [SecretVersion][google.cloud.secretmanager.v1.SecretVersion].
  ///
  /// [google.cloud.secretmanager.v1.SecretVersion]: <doc:SecretVersion>
  ///
  /// @Snippet(path: "SecretManagerService_AccessSecretVersion")
  func accessSecretVersion(
    request: AccessSecretVersionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> AccessSecretVersionResponse

  /// Disables a [SecretVersion][google.cloud.secretmanager.v1.SecretVersion].
  ///
  /// Sets the [state][google.cloud.secretmanager.v1.SecretVersion.state] of the
  /// [SecretVersion][google.cloud.secretmanager.v1.SecretVersion] to
  /// [DISABLED][google.cloud.secretmanager.v1.SecretVersion.State.DISABLED].
  ///
  /// [google.cloud.secretmanager.v1.SecretVersion]: <doc:SecretVersion>
  /// [google.cloud.secretmanager.v1.SecretVersion.State.DISABLED]: <doc:SecretVersion/State/disabled>
  /// [google.cloud.secretmanager.v1.SecretVersion.state]: <doc:SecretVersion/state>
  ///
  /// @Snippet(path: "SecretManagerService_DisableSecretVersion")
  func disableSecretVersion(
    request: DisableSecretVersionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> SecretVersion

  /// Enables a [SecretVersion][google.cloud.secretmanager.v1.SecretVersion].
  ///
  /// Sets the [state][google.cloud.secretmanager.v1.SecretVersion.state] of the
  /// [SecretVersion][google.cloud.secretmanager.v1.SecretVersion] to
  /// [ENABLED][google.cloud.secretmanager.v1.SecretVersion.State.ENABLED].
  ///
  /// [google.cloud.secretmanager.v1.SecretVersion]: <doc:SecretVersion>
  /// [google.cloud.secretmanager.v1.SecretVersion.State.ENABLED]: <doc:SecretVersion/State/enabled>
  /// [google.cloud.secretmanager.v1.SecretVersion.state]: <doc:SecretVersion/state>
  ///
  /// @Snippet(path: "SecretManagerService_EnableSecretVersion")
  func enableSecretVersion(
    request: EnableSecretVersionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> SecretVersion

  /// Destroys a [SecretVersion][google.cloud.secretmanager.v1.SecretVersion].
  ///
  /// Sets the [state][google.cloud.secretmanager.v1.SecretVersion.state] of the
  /// [SecretVersion][google.cloud.secretmanager.v1.SecretVersion] to
  /// [DESTROYED][google.cloud.secretmanager.v1.SecretVersion.State.DESTROYED]
  /// and irrevocably destroys the secret data.
  ///
  /// [google.cloud.secretmanager.v1.SecretVersion]: <doc:SecretVersion>
  /// [google.cloud.secretmanager.v1.SecretVersion.State.DESTROYED]: <doc:SecretVersion/State/destroyed>
  /// [google.cloud.secretmanager.v1.SecretVersion.state]: <doc:SecretVersion/state>
  ///
  /// @Snippet(path: "SecretManagerService_DestroySecretVersion")
  func destroySecretVersion(
    request: DestroySecretVersionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> SecretVersion

  /// Sets the access control policy on the specified secret. Replaces any
  /// existing policy.
  ///
  /// Permissions on
  /// [SecretVersions][google.cloud.secretmanager.v1.SecretVersion] are enforced
  /// according to the policy set on the associated
  /// [Secret][google.cloud.secretmanager.v1.Secret].
  ///
  /// [google.cloud.secretmanager.v1.Secret]: <doc:Secret>
  /// [google.cloud.secretmanager.v1.SecretVersion]: <doc:SecretVersion>
  ///
  /// @Snippet(path: "SecretManagerService_SetIamPolicy")
  func setIamPolicy(
    request: SetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> Policy

  /// Gets the access control policy for a secret.
  /// Returns empty policy if the secret exists and does not have a policy set.
  ///
  /// @Snippet(path: "SecretManagerService_GetIamPolicy")
  func getIamPolicy(
    request: GetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> Policy

  /// Returns permissions that a caller has for the specified secret.
  /// If the secret does not exist, this call returns an empty set of
  /// permissions, not a NOT_FOUND error.
  ///
  /// Note: This operation is designed to be used for building permission-aware
  /// UIs and command-line tools, not for authorization checking. This operation
  /// may "fail open" without warning.
  ///
  /// @Snippet(path: "SecretManagerService_TestIamPermissions")
  func testIamPermissions(
    request: TestIamPermissionsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> TestIamPermissionsResponse

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "SecretManagerService_ListLocations")
  func listLocations(
    request: ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> ListLocationsResponse

  /// Lists information about the supported locations for this service.
  func listLocations(
    byItem: ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Error>

  /// Gets information about a location.
  ///
  /// @Snippet(path: "SecretManagerService_GetLocation")
  func getLocation(
    request: GetLocationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> Location
}

extension Clients {
  /// The recommended implementation for ``SecretManagerService``.
  public class SecretManagerServiceClient: SecretManagerService {
    let inner: any SecretManagerServiceStub

    /// Creates a new `SecretManagerServiceClient` instance.
    public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
      var inner: any SecretManagerServiceStub = try SecretManagerServiceTransport(options)
      if let logger = options.logger {
        inner = SecretManagerServiceLogging(inner, logger: logger)
      }
      self.inner = inner
    }

    /// See `SecretManagerService.listSecrets`
    public func listSecrets(
      request: ListSecretsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> ListSecretsResponse {
      try await self.inner.listSecrets(request: request, options: options)
    }

    /// Lists [Secrets][google.cloud.secretmanager.v1.Secret].
    ///
    /// [google.cloud.secretmanager.v1.Secret]: <doc:Secret>
    public func listSecrets(
      byItem: ListSecretsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Secret, Error> {
      let listRpc = { (token: String) async throws -> ListSecretsResponse in
        var request = byItem
        request.pageToken = token
        return try await self.listSecrets(request: request, options: options)
      }
      return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    /// See `SecretManagerService.createSecret`
    public func createSecret(
      request: CreateSecretRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> Secret {
      try await self.inner.createSecret(request: request, options: options)
    }

    /// See `SecretManagerService.addSecretVersion`
    public func addSecretVersion(
      request: AddSecretVersionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> SecretVersion {
      try await self.inner.addSecretVersion(request: request, options: options)
    }

    /// See `SecretManagerService.getSecret`
    public func getSecret(
      request: GetSecretRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> Secret {
      try await self.inner.getSecret(request: request, options: options)
    }

    /// See `SecretManagerService.updateSecret`
    public func updateSecret(
      request: UpdateSecretRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> Secret {
      try await self.inner.updateSecret(request: request, options: options)
    }

    /// See `SecretManagerService.deleteSecret`
    public func deleteSecret(
      request: DeleteSecretRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self.inner.deleteSecret(request: request, options: options)
    }

    /// See `SecretManagerService.listSecretVersions`
    public func listSecretVersions(
      request: ListSecretVersionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> ListSecretVersionsResponse {
      try await self.inner.listSecretVersions(request: request, options: options)
    }

    /// Lists [SecretVersions][google.cloud.secretmanager.v1.SecretVersion]. This
    /// call does not return secret data.
    ///
    /// [google.cloud.secretmanager.v1.SecretVersion]: <doc:SecretVersion>
    public func listSecretVersions(
      byItem: ListSecretVersionsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<SecretVersion, Error> {
      let listRpc = { (token: String) async throws -> ListSecretVersionsResponse in
        var request = byItem
        request.pageToken = token
        return try await self.listSecretVersions(request: request, options: options)
      }
      return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    /// See `SecretManagerService.getSecretVersion`
    public func getSecretVersion(
      request: GetSecretVersionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> SecretVersion {
      try await self.inner.getSecretVersion(request: request, options: options)
    }

    /// See `SecretManagerService.accessSecretVersion`
    public func accessSecretVersion(
      request: AccessSecretVersionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> AccessSecretVersionResponse {
      try await self.inner.accessSecretVersion(request: request, options: options)
    }

    /// See `SecretManagerService.disableSecretVersion`
    public func disableSecretVersion(
      request: DisableSecretVersionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> SecretVersion {
      try await self.inner.disableSecretVersion(request: request, options: options)
    }

    /// See `SecretManagerService.enableSecretVersion`
    public func enableSecretVersion(
      request: EnableSecretVersionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> SecretVersion {
      try await self.inner.enableSecretVersion(request: request, options: options)
    }

    /// See `SecretManagerService.destroySecretVersion`
    public func destroySecretVersion(
      request: DestroySecretVersionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> SecretVersion {
      try await self.inner.destroySecretVersion(request: request, options: options)
    }

    /// See `SecretManagerService.setIamPolicy`
    public func setIamPolicy(
      request: SetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> Policy {
      try await self.inner.setIamPolicy(request: request, options: options)
    }

    /// See `SecretManagerService.getIamPolicy`
    public func getIamPolicy(
      request: GetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> Policy {
      try await self.inner.getIamPolicy(request: request, options: options)
    }

    /// See `SecretManagerService.testIamPermissions`
    public func testIamPermissions(
      request: TestIamPermissionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> TestIamPermissionsResponse {
      try await self.inner.testIamPermissions(request: request, options: options)
    }

    /// See `SecretManagerService.listLocations`
    public func listLocations(
      request: ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> ListLocationsResponse {
      try await self.inner.listLocations(request: request, options: options)
    }

    /// Lists information about the supported locations for this service.
    public func listLocations(
      byItem: ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Error> {
      let listRpc = { (token: String) async throws -> ListLocationsResponse in
        var request = byItem
        request.pageToken = token
        return try await self.listLocations(request: request, options: options)
      }
      return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    /// See `SecretManagerService.getLocation`
    public func getLocation(
      request: GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> Location {
      try await self.inner.getLocation(request: request, options: options)
    }
  }
}

// Default implementations
extension SecretManagerService {
  public func listSecrets(request: ListSecretsRequest) async throws -> ListSecretsResponse {
    try await self.listSecrets(request: request, options: .init())
  }

  public func listSecrets(
    request: ListSecretsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> ListSecretsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listSecrets(byItem: ListSecretsRequest) throws -> any AsyncSequence<Secret, Error> {
    try self.listSecrets(byItem: byItem, options: .init())
  }

  public func listSecrets(
    byItem: ListSecretsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Secret, Error> {
    let listRpc = { (token: String) async throws -> ListSecretsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func createSecret(request: CreateSecretRequest) async throws -> Secret {
    try await self.createSecret(request: request, options: .init())
  }

  public func createSecret(
    request: CreateSecretRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> Secret {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func addSecretVersion(request: AddSecretVersionRequest) async throws -> SecretVersion {
    try await self.addSecretVersion(request: request, options: .init())
  }

  public func addSecretVersion(
    request: AddSecretVersionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> SecretVersion {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getSecret(request: GetSecretRequest) async throws -> Secret {
    try await self.getSecret(request: request, options: .init())
  }

  public func getSecret(
    request: GetSecretRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> Secret {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateSecret(request: UpdateSecretRequest) async throws -> Secret {
    try await self.updateSecret(request: request, options: .init())
  }

  public func updateSecret(
    request: UpdateSecretRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> Secret {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteSecret(request: DeleteSecretRequest) async throws {
    try await self.deleteSecret(request: request, options: .init())
  }

  public func deleteSecret(
    request: DeleteSecretRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listSecretVersions(request: ListSecretVersionsRequest) async throws
    -> ListSecretVersionsResponse
  {
    try await self.listSecretVersions(request: request, options: .init())
  }

  public func listSecretVersions(
    request: ListSecretVersionsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> ListSecretVersionsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listSecretVersions(byItem: ListSecretVersionsRequest) throws -> any AsyncSequence<
    SecretVersion, Error
  > {
    try self.listSecretVersions(byItem: byItem, options: .init())
  }

  public func listSecretVersions(
    byItem: ListSecretVersionsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<SecretVersion, Error> {
    let listRpc = { (token: String) async throws -> ListSecretVersionsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getSecretVersion(request: GetSecretVersionRequest) async throws -> SecretVersion {
    try await self.getSecretVersion(request: request, options: .init())
  }

  public func getSecretVersion(
    request: GetSecretVersionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> SecretVersion {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func accessSecretVersion(request: AccessSecretVersionRequest) async throws
    -> AccessSecretVersionResponse
  {
    try await self.accessSecretVersion(request: request, options: .init())
  }

  public func accessSecretVersion(
    request: AccessSecretVersionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> AccessSecretVersionResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func disableSecretVersion(request: DisableSecretVersionRequest) async throws
    -> SecretVersion
  {
    try await self.disableSecretVersion(request: request, options: .init())
  }

  public func disableSecretVersion(
    request: DisableSecretVersionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> SecretVersion {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func enableSecretVersion(request: EnableSecretVersionRequest) async throws -> SecretVersion
  {
    try await self.enableSecretVersion(request: request, options: .init())
  }

  public func enableSecretVersion(
    request: EnableSecretVersionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> SecretVersion {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func destroySecretVersion(request: DestroySecretVersionRequest) async throws
    -> SecretVersion
  {
    try await self.destroySecretVersion(request: request, options: .init())
  }

  public func destroySecretVersion(
    request: DestroySecretVersionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> SecretVersion {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func setIamPolicy(request: SetIamPolicyRequest) async throws -> Policy {
    try await self.setIamPolicy(request: request, options: .init())
  }

  public func setIamPolicy(
    request: SetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> Policy {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getIamPolicy(request: GetIamPolicyRequest) async throws -> Policy {
    try await self.getIamPolicy(request: request, options: .init())
  }

  public func getIamPolicy(
    request: GetIamPolicyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> Policy {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func testIamPermissions(request: TestIamPermissionsRequest) async throws
    -> TestIamPermissionsResponse
  {
    try await self.testIamPermissions(request: request, options: .init())
  }

  public func testIamPermissions(
    request: TestIamPermissionsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> TestIamPermissionsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listLocations(request: ListLocationsRequest) async throws -> ListLocationsResponse {
    try await self.listLocations(request: request, options: .init())
  }

  public func listLocations(
    request: ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> ListLocationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listLocations(byItem: ListLocationsRequest) throws -> any AsyncSequence<
    GoogleCloudLocation.Location, Error
  > {
    try self.listLocations(byItem: byItem, options: .init())
  }

  public func listLocations(
    byItem: ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Error> {
    let listRpc = { (token: String) async throws -> ListLocationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getLocation(request: GetLocationRequest) async throws -> Location {
    try await self.getLocation(request: request, options: .init())
  }

  public func getLocation(
    request: GetLocationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> Location {
    throw GoogleCloudGax.RequestError.unimplemented
  }
}
