// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A secret version resource in the Secret Manager API.
public struct SecretVersion: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. The resource name of the
  /// [SecretVersion][google.cloud.secretmanager.v1.SecretVersion] in the format
  /// `projects/*/secrets/*/versions/*`.
  ///
  /// [SecretVersion][google.cloud.secretmanager.v1.SecretVersion] IDs in a
  /// [Secret][google.cloud.secretmanager.v1.Secret] start at 1 and are
  /// incremented for each subsequent version of the secret.
  ///
  /// [google.cloud.secretmanager.v1.Secret]: <doc:Secret>
  /// [google.cloud.secretmanager.v1.SecretVersion]: <doc:SecretVersion>
  public var name: Swift.String = Swift.String()

  /// Output only. The time at which the
  /// [SecretVersion][google.cloud.secretmanager.v1.SecretVersion] was created.
  ///
  /// [google.cloud.secretmanager.v1.SecretVersion]: <doc:SecretVersion>
  public var createTime: GoogleWKT.Timestamp? = nil

  /// Output only. The time this
  /// [SecretVersion][google.cloud.secretmanager.v1.SecretVersion] was destroyed.
  /// Only present if [state][google.cloud.secretmanager.v1.SecretVersion.state]
  /// is
  /// [DESTROYED][google.cloud.secretmanager.v1.SecretVersion.State.DESTROYED].
  ///
  /// [google.cloud.secretmanager.v1.SecretVersion]: <doc:SecretVersion>
  /// [google.cloud.secretmanager.v1.SecretVersion.State.DESTROYED]: <doc:SecretVersion/State/destroyed>
  /// [google.cloud.secretmanager.v1.SecretVersion.state]: <doc:SecretVersion/state>
  public var destroyTime: GoogleWKT.Timestamp? = nil

  /// Output only. The current state of the
  /// [SecretVersion][google.cloud.secretmanager.v1.SecretVersion].
  ///
  /// [google.cloud.secretmanager.v1.SecretVersion]: <doc:SecretVersion>
  public var state: SecretVersion.State = SecretVersion.State()

  /// The replication status of the
  /// [SecretVersion][google.cloud.secretmanager.v1.SecretVersion].
  ///
  /// [google.cloud.secretmanager.v1.SecretVersion]: <doc:SecretVersion>
  public var replicationStatus: ReplicationStatus? = nil

  /// Output only. Etag of the currently stored
  /// [SecretVersion][google.cloud.secretmanager.v1.SecretVersion].
  ///
  /// [google.cloud.secretmanager.v1.SecretVersion]: <doc:SecretVersion>
  public var etag: Swift.String = Swift.String()

  /// Output only. True if payload checksum specified in
  /// [SecretPayload][google.cloud.secretmanager.v1.SecretPayload] object has
  /// been received by
  /// [SecretManagerService][google.cloud.secretmanager.v1.SecretManagerService]
  /// on
  /// [SecretManagerService.AddSecretVersion][google.cloud.secretmanager.v1.SecretManagerService.AddSecretVersion].
  ///
  /// [google.cloud.secretmanager.v1.SecretManagerService]: <doc:SecretManagerServiceClient>
  /// [google.cloud.secretmanager.v1.SecretManagerService.AddSecretVersion]: <doc:SecretManagerServiceClient/addSecretVersion(request:options:)>
  /// [google.cloud.secretmanager.v1.SecretPayload]: <doc:SecretPayload>
  public var clientSpecifiedPayloadChecksum: Swift.Bool = Swift.Bool()

  /// Optional. Output only. Scheduled destroy time for secret version.
  /// This is a part of the Delayed secret version destroy feature. For a
  /// Secret with a valid version destroy TTL, when a secert version is
  /// destroyed, version is moved to disabled state and it is scheduled for
  /// destruction Version is destroyed only after the scheduled_destroy_time.
  public var scheduledDestroyTime: GoogleWKT.Timestamp? = nil

  /// Output only. The customer-managed encryption status of the
  /// [SecretVersion][google.cloud.secretmanager.v1.SecretVersion]. Only
  /// populated if customer-managed encryption is used and
  /// [Secret][google.cloud.secretmanager.v1.Secret] is a regionalized secret.
  ///
  /// [google.cloud.secretmanager.v1.Secret]: <doc:Secret>
  /// [google.cloud.secretmanager.v1.SecretVersion]: <doc:SecretVersion>
  public var customerManagedEncryption: CustomerManagedEncryptionStatus? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `SecretVersion`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SecretVersion().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let destroyTime = CodingKeys(stringValue: "destroyTime")
    static let state = CodingKeys(stringValue: "state")
    static let replicationStatus = CodingKeys(stringValue: "replicationStatus")
    static let etag = CodingKeys(stringValue: "etag")
    static let clientSpecifiedPayloadChecksum = CodingKeys(
      stringValue: "clientSpecifiedPayloadChecksum")
    static let scheduledDestroyTime = CodingKeys(stringValue: "scheduledDestroyTime")
    static let customerManagedEncryption = CodingKeys(stringValue: "customerManagedEncryption")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "createTime",
      "destroyTime",
      "state",
      "replicationStatus",
      "etag",
      "clientSpecifiedPayloadChecksum",
      "scheduledDestroyTime",
      "customerManagedEncryption",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    self.createTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .createTime)
    self.destroyTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .destroyTime)
    if let value = try container.decodeIfPresent(SecretVersion.State.self, forKey: .state) {
      self.state = value
    }
    self.replicationStatus = try container.decodeIfPresent(
      ReplicationStatus.self, forKey: .replicationStatus)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .etag) {
      self.etag = value
    }
    if let value = try container.decodeIfPresent(
      Swift.Bool.self, forKey: .clientSpecifiedPayloadChecksum)
    {
      self.clientSpecifiedPayloadChecksum = value
    }
    self.scheduledDestroyTime = try container.decodeIfPresent(
      GoogleWKT.Timestamp.self, forKey: .scheduledDestroyTime)
    self.customerManagedEncryption = try container.decodeIfPresent(
      CustomerManagedEncryptionStatus.self, forKey: .customerManagedEncryption)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.destroyTime, forKey: .destroyTime)
    try container.encode(self.state, forKey: .state)
    try container.encodeIfPresent(self.replicationStatus, forKey: .replicationStatus)
    try container.encode(self.etag, forKey: .etag)
    try container.encode(
      self.clientSpecifiedPayloadChecksum, forKey: .clientSpecifiedPayloadChecksum)
    try container.encodeIfPresent(self.scheduledDestroyTime, forKey: .scheduledDestroyTime)
    try container.encodeIfPresent(
      self.customerManagedEncryption, forKey: .customerManagedEncryption)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The state of a
  /// [SecretVersion][google.cloud.secretmanager.v1.SecretVersion], indicating if
  /// it can be accessed.
  ///
  /// [google.cloud.secretmanager.v1.SecretVersion]: <doc:SecretVersion>
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum State: Codable, Equatable, Sendable {
    /// Not specified. This value is unused and invalid.
    case unspecified
    /// The [SecretVersion][google.cloud.secretmanager.v1.SecretVersion] may be
    /// accessed.
    ///
    /// [google.cloud.secretmanager.v1.SecretVersion]: <doc:SecretVersion>
    case enabled
    /// The [SecretVersion][google.cloud.secretmanager.v1.SecretVersion] may not
    /// be accessed, but the secret data is still available and can be placed
    /// back into the
    /// [ENABLED][google.cloud.secretmanager.v1.SecretVersion.State.ENABLED]
    /// state.
    ///
    /// [google.cloud.secretmanager.v1.SecretVersion]: <doc:SecretVersion>
    /// [google.cloud.secretmanager.v1.SecretVersion.State.ENABLED]: <doc:SecretVersion/State/enabled>
    case disabled
    /// The [SecretVersion][google.cloud.secretmanager.v1.SecretVersion] is
    /// destroyed and the secret data is no longer stored. A version may not
    /// leave this state once entered.
    ///
    /// [google.cloud.secretmanager.v1.SecretVersion]: <doc:SecretVersion>
    case destroyed
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .enabled: return 1
      case .disabled: return 2
      case .destroyed: return 3
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .enabled: return "ENABLED"
      case .disabled: return "DISABLED"
      case .destroyed: return "DESTROYED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "ENABLED": self = .enabled
      case "DISABLED": self = .disabled
      case "DESTROYED": self = .destroyed
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .enabled
      case 2: self = .disabled
      case 3: self = .destroyed
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("STATE_UNSPECIFIED")
      case .enabled: return try container.encode("ENABLED")
      case .disabled: return try container.encode("DISABLED")
      case .destroyed: return try container.encode("DESTROYED")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.secretmanager.v1.SecretVersion"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
