// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

import GoogleCloudLocation
import GoogleCloudWkt
import GoogleIamV1

/// A secret payload resource in the Secret Manager API. This contains the
/// sensitive secret payload that is associated with a
/// [SecretVersion][google.cloud.secretmanager.v1.SecretVersion].
public struct SecretPayload: Codable, Equatable, GoogleCloudWkt._AnyPackable {
  /// The secret data. Must be no larger than 64KiB.
  public var data: Data

  /// Optional. If specified,
  /// [SecretManagerService][google.cloud.secretmanager.v1.SecretManagerService]
  /// will verify the integrity of the received
  /// [data][google.cloud.secretmanager.v1.SecretPayload.data] on
  /// [SecretManagerService.AddSecretVersion][google.cloud.secretmanager.v1.SecretManagerService.AddSecretVersion]
  /// calls using the crc32c checksum and store it to include in future
  /// [SecretManagerService.AccessSecretVersion][google.cloud.secretmanager.v1.SecretManagerService.AccessSecretVersion]
  /// responses. If a checksum is not provided in the
  /// [SecretManagerService.AddSecretVersion][google.cloud.secretmanager.v1.SecretManagerService.AddSecretVersion]
  /// request, the
  /// [SecretManagerService][google.cloud.secretmanager.v1.SecretManagerService]
  /// will generate and store one for you.
  ///
  /// The CRC32C value is encoded as a Int64 for compatibility, and can be
  /// safely downconverted to uint32 in languages that support this type.
  /// https://cloud.google.com/apis/design/design_patterns#integer_types
  public var dataCrc32C: Int64?

  /// Initialize a new instance of `SecretPayload`.
  public init(
    data: Data = Data(),
    dataCrc32C: Int64? = nil,
  ) {
    self.data = data
    self.dataCrc32C = dataCrc32C
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.secretmanager.v1.SecretPayload"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
