// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

import GoogleCloudLocation
import GoogleCloudWkt
import GoogleIamV1

/// A Pub/Sub topic which Secret Manager will publish to when control plane
/// events occur on this secret.
public struct Topic: Codable, Equatable, GoogleCloudWkt._AnyPackable, Sendable {
  /// Identifier. The resource name of the Pub/Sub topic that will be published
  /// to, in the following format: `projects/*/topics/*`. For publication to
  /// succeed, the Secret Manager service agent must have the
  /// `pubsub.topic.publish` permission on the topic. The Pub/Sub Publisher role
  /// (`roles/pubsub.publisher`) includes this permission.
  public var name: String

  /// Initialize a new instance of `Topic`.
  public init(
    name: String = String(),
  ) {
    self.name = name
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.secretmanager.v1.Topic"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
