// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation

import GoogleCloudLocation
import GoogleCloudWkt
import GoogleIamV1

/// Request message for
/// [SecretManagerService.UpdateSecret][google.cloud.secretmanager.v1.SecretManagerService.UpdateSecret].
public struct UpdateSecretRequest: Codable, Equatable {
  /// Required. [Secret][google.cloud.secretmanager.v1.Secret] with updated field
  /// values.
  public var secret: Secret?

  /// Required. Specifies the fields to be updated.
  public var updateMask: GoogleCloudWkt.FieldMask?

  /// Initialize a new instance of `UpdateSecretRequest`.
  public init(
    secret: Secret? = nil,
    updateMask: GoogleCloudWkt.FieldMask? = nil,
  ) {
    self.secret = secret
    self.updateMask = updateMask
  }
}
